### PR TITLE
Update to support new version of addon-resizer

### PR DESCRIPTION
**Pull request by carlosedp**
Fix for #2366.

Corrected the parameter to reflect new version. Also I've updated the references for the images and version.

### CODE REVIEW

**Comment by brancz** [comment]
Due to a little of an unfortunate setup, you need to create an extra commit, that just has the content/modifications that happen when you run `jb update` in `contrib/kube-prometheus/`, and then `make clean generate-in-docker` in the root of the repo. Sorry for the inconvenience.

**Comment by carlosedp** [comment]
Done!

**Comment by brancz** [comment]
:S looks like that needs a rebase now

**Comment by carlosedp** [comment]
Maybe it's ok now? :)

**Comment by s-urbaniak** [comment]
@carlosedp it seems you did a merge commit instead of a git rebase, so quite some commits were pulled in. Do you mind to do a real git rebase such that only your commits appear in this PR?

**Comment by carlosedp** [comment]
Now I hope it's OK. Sorry about messing this up @s-urbaniak. :)

**Comment by carlosedp** [comment]
Thanks for the patience guys.

**Pull request merged**
