### PR TITLE
tests: Fix jsonnet docker build

### PR DESCRIPTION
**Pull request by mxinden**
According to the docker file reference [1] `ADD` will unpack recognized
compression formats as a directory. There is no need for us anymore to
unpack jsonnet.

[1] https://docs.docker.com/engine/reference/builder/#add

//CC @bison

### CODE REVIEW

**Comment by mxinden** [comment]
Let's see if this is a valid fix.

**Comment by brancz** [comment]
Feel free to merge on your behalf once working

**Comment by brancz** [comment]
@coreosbot test this please.

**Comment by brancz** [comment]
@mxinden out of curiosity, what is the docker version on the jenkins machine? As I tried this with the version I have installed and it doesn't seem to work.

**Comment by brancz** [comment]
Actually just upgraded to latest docker and it now works fine.

**Comment by mxinden** [comment]
@brancz But you are not facing the `cannot remove '/tmp/jsonnet-0.9.4/benchmarks': Directory not empty` locally even though we are using `rm -rf`, right?

`$ docker version` on the Jenkins worker:
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Commit e6275ac744d5d18a098db4710a1db518887a4bf2 seems to fix the issue. This should only stay temporary, but I am fine with merging here so you are no longer blocked.

@bison Could you have a look why build # [201](https://jenkins-monitoring.prod.coreos.systems/job/po-tests-pr/201/console) is failing?

**Comment by brancz** [comment]
@mxinden I did some additional local testing and it seems like the `ADD` behavior is quite different across releases, so I'd prefer to stick with just running commands where we can. The `Dockerfile` that ended up working for me is:

```
FROM golang:1.8-stretch

RUN apt-get update -y && apt-get install -y g++ make git python-pip
RUN cd /tmp && wget https://github.com/google/jsonnet/archive/v0.9.4.tar.gz && tar xvfz v0.9.4.tar.gz && cd jsonnet-0.9.4 && make && mv jsonnet /usr/local/bin

RUN git clone https://github.com/ksonnet/ksonnet-lib.git /ksonnet-lib && cd /ksonnet-lib && git checkout bd6b2d618d6963ea6a81fcc5623900d8ba110a32

RUN pip install json2yaml
RUN mkdir -p /go/src/github.com/coreos/prometheus-operator
WORKDIR /go/src/github.com/coreos/prometheus-operator
```

Could you try that out? The point is, if generating locally doesn't work, we'll see if it fails on CI, but can't do anything about it :) . Thanks!

**Comment by mxinden** [comment]
@brancz Adjusted accordingly. Lets see if 0d55379 fixes it.

**Comment by brancz** [comment]
Alright as it passed on CI and works for me this is good to merge. Thanks for your efforts @mxinden !

**Comment by mxinden** [comment]
@bison For me this looks like a valid fix. No need to further look into this. Thanks for your help!

**Pull request merged**
