### PR TITLE
Make resource limit and request of Prometheus configurable.

### PR DESCRIPTION
**Pull request by ryotarai**
This PR introduces `_config.prometheus.resourceRequests` and `_config.prometheus.resourceLimits` to configure resources of Prometheus Pods.

### CODE REVIEW

**Comment by metalmatze** [comment]
I'd be ok with that change but don't think it's really necessary. What do others think?

**Comment by brancz** [comment]
I don't see a patch being any more complicated than the configuration. I'd prefer this as a jsonnet patch as well.

**Comment by metalmatze** [comment]
kube-prometheus just moved to https://github.com/coreos/kube-prometheus. 
See [contrib/kube-prometheus/README.md](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/README.md) for details.

Thank you for your contribution and sorry for the inconvenience!

**Comment by pgier** [comment]
Closing this since the relevant code has moved to https://github.com/coreos/kube-prometheus

**Pull request closed without merging**
