### PR TITLE
Add readinessProbe for grafana Helm

### PR DESCRIPTION
**Pull request by sebglon**
#934

### CODE REVIEW

**Comment by gianrubio** [comment]
Based on the discussion on https://github.com/grafana/grafana/issues/3302#issuecomment-297066201 I'd suggest you to change the readiness probe endpoint to ` /api/health `

**Comment by sebglon** [comment]
OK

**Comment by sebglon** [comment]
@gianrubio Version bumped and merged with master

**Comment by gianrubio** [comment]
On green I'll merge it, thanks @sebglon

**Comment by gianrubio** [comment]
thanks @sebglon

**Pull request merged**
