### PR TITLE
Update node alert rules

### PR DESCRIPTION
**Pull request by aleerizw**
Rules weren't updated after https://github.com/coreos/prometheus-operator/pull/1433 was merged

### CODE REVIEW

**Comment by aleerizw** [comment]
The CI failure doesn't look related, can I re-trigger the pipeline somehow?

**Comment by brancz** [comment]
That's a flaky test, sorry about that, I retriggered the job.

**Comment by aleerizw** [comment]
Looks like the build is canceled?

**Comment by aleerizw** [comment]
CI faield again :sob:

**Pull request merged**
