### PR TITLE
Adding kustomization files for remote bases

### PR DESCRIPTION
**Pull request by coryodaniel**
Adds support to allow kustomize users to point to a [remote
base](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md) of the prometheus-operator and kube-prometheus. Now that kustomize is a part of kubectl, this is provides a very simple way of installing prometheus-operator and kube-prometheus with no additional tools besides kubectl.

* [Added] kustomization.yaml: hardcoded kustomization base for prometheus-operator
bundle.yaml
* [Added] contrib/kube-prometheus/hack/generate-kustomization.sh: script to generate kustomization base for kube-prometheus

### CODE REVIEW

**Comment by coryodaniel** [comment]
Closes #2391

**Comment by brancz** [comment]
I'm generally for this change, but as all the other manifests in this repo are generated with jsonnet, I think this should be as well.

**Comment by coryodaniel** [comment]
\*searches for jsonnet tutorials\*
learning jsonnet

**Comment by coryodaniel** [comment]
Closing in favor of: https://github.com/coreos/prometheus-operator/pull/2497

**Pull request closed without merging**
