### PR TITLE
Updated README for removing CRDs generated by v1 api.

### PR DESCRIPTION
**Pull request by rahulwa**
When I started working on this project I figured that a few steps were missing.  I have added them in the PR.

### CODE REVIEW

**Comment by brancz** [comment]
I don't quite understand why this is necessary, can you explain?

**Comment by rahulwa** [comment]
Currently `prometheus-operator` generates `alertmanagers.monitoring.coreos.com`, `prometheuses.monitoring.coreos.com ` and `servicemonitors.monitoring.coreos.com ` CRDs but [Removal section on README](https://github.com/coreos/prometheus-operator#removal) is missing the instruction for removing them.

README is the first place to look for while getting started with any project. README should be correct and complete for any instruction that it mentions.

**Comment by brancz** [comment]
If the new entries work, then I believe we can remove the old ones, as each of these should only exist once under one name, so it seems odd that we need to remove them twice

**Comment by rahulwa** [comment]
Agreed. I have removed old entries.

**Comment by brancz** [comment]
Thansk! lgtm :+1:

**Pull request merged**
