### PR TITLE
allow seting volume name via volumetemplateclaimtemplate in prom and alertmanager

### PR DESCRIPTION
**Pull request by rmartinez3**
This pull request allows users that have more control over setting volumeclaim template. Specifically the volume claim name . If a person doesn't set the name then it is inserted for you by default as it has been doing for statefulset. This is needed more since using gluster as a storageclass , the name is too long . Giving user the ability to set their name for themselves, people that want to migrate to using gluster won't have this issue anymore since the user can set a short name and wont break anything for people already using volume claim template.

### CODE REVIEW

**Comment by brancz** [comment]
Have you tried this with multiple replicas? I would think that setting the name explicitly forces the PVC to have that very name, no?

**Comment by rmartinez3** [comment]
Using volumeclaimtemplate via prom

> storage:
>   volumeClaimTemplate:
>       - metadata:
>            name: data
>        spec:
>          accessModes:
>            - ReadWriteOnce
>          storageClassName: monitoring-prometheus
>          resources:
>            requests:
>              storage: 250Gi
> 

`data-prometheus-prometheus-0       Bound     monitoring-prometheus-db-0   250Gi      RWO            monitoring-prometheus     2h`
`data-prometheus-prometheus-1       Bound        monitoring-prometheus-db-1 250Gi  RWO                                                   monitoring-prometheus     2h`

when scaling prom to two. likewise is the same with alertmanager

**Comment by brancz** [comment]
Generally this lgtm, but the e2e tests seem to be failing. You can run them on a local minikube by building the container images with `make image` and then running the e2e tests with `make test-e2e`. Then you can use kubectl to figure out what's going wrong.

**Comment by rmartinez3** [comment]
Thanks for the info on testing. Updated and tests have passed.

**Comment by brancz** [comment]
Thanks! This lgtm :+1:

**Comment by leeyan85** [comment]
I set alertmanager values file ,  storage configuration like below
```
## Alertmanager StorageSpec for persistent data
## Ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md
##
storageSpec: {}
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: glusterfs-prometheus
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 3Gi
#    selector: {}
```


run the  install command like 

`helms install --name alertmanager --namespace=monitoring helm/alertmanager
`

but the pvc can't be created, the  error like below
  ```
Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  ProvisioningFailed  19s   persistentvolume-controller  Failed to provision volume with StorageClass "glusterfs-prometheus": create volume error: failed to create endpoint/service error creating service: Service "glusterfs-dynamic-alertmanager-alertmanager-db-alertmanager-alertmanager-0" is invalid: metadata.name: Invalid value: "glusterfs-dynamic-alertmanager-alertmanager-db-alertmanager-alertmanager-0": must be no more than 63 characters

```

**Comment by Doublemine** [comment]
@leeyan85 If you deploy `prometeheus-operator` by helm, maybe you should upgrade the `values.yaml`： 
 - `quay.io/coreos/prometheus-config-reloader:v0.20.0` to `quay.io/coreos/prometheus-config-reloader:v0.24.0`
 -  `quay.io/coreos/prometheus-operator:v0.20.0` to `quay.io/coreos/prometheus-operator:v0.24.0`

That's work for me.

**Comment by leeyan85** [comment]
@Doublemine  , updated the `helm/prometheus-operator/values.yaml ` values,  followings  are my deploy info ? 

```
[root@LFTd-k8s-master01 prometheus-operator]# kubectl describe deploy/prometheus-operator -n monitoring  
Name:                   prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Tue, 23 Oct 2018 16:41:18 +0800
Labels:                 app=prometheus-operator
                        chart=prometheus-operator-0.0.29
                        heritage=Tiller
                        operator=prometheus
                        release=prometheus-operator
Annotations:            deployment.kubernetes.io/revision=1
Selector:               app=prometheus-operator,operator=prometheus,release=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=prometheus-operator
                    operator=prometheus
                    release=prometheus-operator
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:  quay.io/coreos/prometheus-operator:v0.24.0
    Port:   8080/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --prometheus-config-reloader=**quay.io/coreos/prometheus-config-reloader:v0.24.0**
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-6c6d5868db (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  7m    deployment-controller  Scaled up replica set prometheus-operator-6c6d5868db to 1
```

I still got the same issue. 

```
[root@LFTd-k8s-master01 prometheus-operator]# kubectl get pvc -n monitoring  
NAME                                               STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS           AGE
prometheus-prometheus-db-prometheus-prometheus-0   Pending                                       glusterfs-prometheus   11m
```
```
[root@LFTd-k8s-master01 prometheus-operator]# kubectl describe pvc prometheus-prometheus-db-prometheus-prometheus-0 -n monitoring  
Name:          prometheus-prometheus-db-prometheus-prometheus-0
Namespace:     monitoring
StorageClass:  glusterfs-prometheus
Status:        Pending
Volume:        
Labels:        app=prometheus
               prometheus=prometheus
Annotations:   volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/glusterfs
Finalizers:    []
Capacity:      
Access Modes:  
Events:
  Type     Reason              Age                 From                         Message
  ----     ------              ----                ----                         -------
  Warning  ProvisioningFailed  22s (x27 over 13m)  persistentvolume-controller  Failed to provision volume with StorageClass "glusterfs-prometheus": create volume error: failed to create endpoint/service error creating service: Service "glusterfs-dynamic-prometheus-prometheus-db-prometheus-prometheus-0" is invalid: metadata.name: Invalid value: "glusterfs-dynamic-prometheus-prometheus-db-prometheus-prometheus-0": must be no more than 63 characters
[root@LFTd-k8s-master01 prometheus-operator]# 
```

**Comment by leeyan85** [comment]
@Doublemine ， Thanks very much, it works for me.

**Pull request merged**
