### PR TITLE
added tolerations field

### PR DESCRIPTION
**Pull request by ayk33**
Changes to address #1234

### CODE REVIEW

**Comment by gianrubio** [comment]
CI is failing, most probably because you didn’t bump the chart version, please follow this guide https://github.com/coreos/prometheus-operator/blob/master/helm/README.md

**Comment by ayk33** [comment]
My fork is a few days old so it looks like there is a conflict with the Charts.yaml files.

**Comment by ayk33** [comment]
Thanks for taking care of that. I'll go ahead and close this PR.

**Comment by ayk33** [comment]
Closed prematurely. Reopened the issue.

**Pull request merged**
