### PR TITLE
helm/prometheus: fix additionalAlertManagerConfigs template condition

### PR DESCRIPTION
**Pull request by sdurrheimer**

### CODE REVIEW

**Comment by alice-sawatzky** [comment]
oops, yikes, my bad!

**Comment by jdoupe** [comment]
Thanks for fixing this.

I had a secondary issue with it however.  What happens if you don't have `.Values.alertingEndpoints` AND you don't want the default `alerting` settings?  (i.e. you ONLY want what you've put in the `additionalAlertManagerConfigs`?

So, I did something like:
```
--- a/helm/prometheus/templates/prometheus.yaml
+++ b/helm/prometheus/templates/prometheus.yaml
@@ -20,12 +20,18 @@ spec:
   alerting:
     alertmanagers:
 {{ toYaml .Values.alertingEndpoints | indent 6 }}
+{{- else if .Values.additionalAlertManagerConfigs }}
 {{- else }}
   alerting:
     alertmanagers:
       - namespace: {{ .Release.Namespace }}
         name: {{ printf "%s-alertmanager" .Release.Name | trunc 63 | trimSuffix "-" }}
         port: http
+{{- end }}
+{{- if .Values.additionalAlertManagerConfigs }}
+  additionalAlertManagerConfigs:
+    name: prometheus-{{ .Release.Name }}-additional-alertmanager-configs
+    key: additional-alertmanager-configs.yaml
 {{- end }}
   baseImage: "{{ .Values.image.repository }}"
 {{- if .Values.externalLabels }}
```

(Sorry to glob onto this issue)

**Comment by richerve** [comment]
@alice-sawatzky https://github.com/coreos/prometheus-operator/pull/1586

**Comment by sdurrheimer** [comment]
Hi @gianrubio, could you take a look ?

**Comment by metalmatze** [comment]
The Helm chart has moved to https://github.com/helm/charts/tree/master/stable/prometheus-operator please open a PR there.
Thank you for your contribution!

**Pull request closed without merging**
