### PR TITLE
Mount custom secrets

### LINKED ISSUE #250: kube-prometheus: monitoring authenticated kubelets
**What did you do?**

Deployed kube-prometheus

**What did you expect to see?**

kubelet being scraped

**What did you see instead? Under which circumstances?**

kubelet not being scraped

**Environment**

Tectonic v1.5.5 via Terraform AWS

The problem is that Tectonic has certificate protection on these endpoints; need to figure out how to configure this.

screen shot 2017-03-30 at 1 25 15 am

### PR DESCRIPTION
**Pull request by brancz**
This enables the ability to mount custom secrets into a Prometheus to be able to use those for the bearer token or TLS config in the Endpoint object of the ServiceMonitor.

@fabxc @mxinden 

Closes #250  and #251

### CODE REVIEW

**Comment by fabxc** [comment]
Looks good in general. Still having somewhat of an itch about the documented path we provide... but all auto-resolve solutions I can think of right now seem prone to unexpected behavior too – at least if we assume that people may provide their own prometheus image with embedded secrets.

**Comment by brancz** [comment]
So far I assumed the `baseImage` is purely there to be able to specify another location of but otherwise equivalent image repository to the canonical repository on quay.io. The use case being that the image has to come from a custom registry because of audit/security reasons.

**Comment by brancz** [comment]
We would have the same concerns with the prometheus-config-reloader writing the rules to a specific location.

**Comment by fabxc** [comment]
Yea, I think it is generally reasonable to assume people use secrets. But they could generally host their own image which is our image as a base + directly integrated certs. Those could have a random location basically – not sure whether this has to be supported though. For rules I think this is less likely.

If we assume people don't do anything like this, we could say that all cert and bearer token files should be simply specified as `<secretname>/<path_in_secret>`.

**Comment by brancz** [comment]
As we've identified inconsistencies with where the serviceaccount secret is mounted and the inability to validate TPRs we will go with the way this is currently implemented.

**Comment by brancz** [comment]
While mounting the secrets is now working I still have to figure out how to configure it properly so protected kubelets such as in #250 can be scraped.

**Comment by brancz** [comment]
I validated, that this works for secure kubelets. Merging.

**Comment by t-trout** [comment]
Could someone please provide an example of how to do this using Promtheus-Operator? I have been unsuccessful getting access to the ETCD nodes (the endpoints are exposed, but since it requires HTTPS, I need to use the etcd-client.pem and etcd-client-key.pem files generated by kube-AWS when the k8s cluster was generated).

I've tried specifying the tlsConfig for the ETCD service monitor with the caFile, certFile, and keyFile values, but since these are located on the underlying node and not in the Prometheus pod, it can't find them. I tried to create a volume with a hostPath to the location of these files within my Prometheus.yaml file, but since Prometheus is spun up by Prometheus-Operator, the volume isn't showing up (the volume does not show up when I look at the pods)

I'm thinking that maybe the best approach would be to create a secret with the 3 tlsConfig files (etcd-client.pem, etcd-client-key.pem, ca.pem) but an example showing how to mount the secret in the Prometheus.yaml file and then specifying the secret in my ETCD serviceMonitor would be so wonderfully helpful. Thanks -

**Pull request merged**
