### PR TITLE
tests: Fix password variable definition

### PR DESCRIPTION
**Pull request by mxinden**
The installer changed the tectonic_admin_password_hash variable to
tectonic_admin_password.

### CODE REVIEW

**Comment by brancz** [comment]
> TooManyBuckets: You have attempted to create more buckets than allowed

**Comment by mxinden** [comment]
@coreosbot please test this

**Comment by brancz** [comment]
Same as before.

**Comment by mxinden** [comment]
@coreosbot please test this

**Comment by mxinden** [comment]
test this please

**Comment by mxinden** [comment]
@brancz back on green. Please merge if this looks good to you.

**Comment by brancz** [comment]
Thanks!

**Pull request merged**
