### PR TITLE
Replace SharedIndexInformers with nonshared version of them

### PR DESCRIPTION
**Pull request by redbaron**
Informers were not really shared at all, so to convey
what is  actually happening clearer, use of less powerfull
abstractions is desirable.

### CODE REVIEW

**Comment by brancz** [comment]
I realize we don't do this today, but the statefulset and secrets informers should actually be shared between the prometheus and alertmanager controllers.

**Comment by brancz** [comment]
That sounds good to me.

**Comment by metalmatze** [comment]
The e2e tests seem to timeout. I can't see anything in the Travis logs that seems obvious. Maybe debugging this on a machine with `make test-e2e` makes sense?!

**Comment by redbaron** [comment]
I'll try, is  it just minikube it needs?

**Comment by redbaron** [comment]
It doesn't make it more tidy or performant, so I am closing it, it doesn't worth it

**Pull request closed without merging**
