### PR TITLE
Fix docu concerning initial deployment

### PR DESCRIPTION
**Pull request by stroebitzer**
After cloning the repo I wanted to deploy kube-prometheus into my running minikube. I did the steps mentioned in the docu which brought me to the following exception:

namespace "monitoring" created
error: the path "manifests/prometheus-operator" does not exist
Waiting for Operator to register custom resource definitions.................................................................................................................^C

### CODE REVIEW

**Comment by brancz** [comment]
I think this is more confusing then before, because a lot of the scripts in `hack/` have to be executed from that directory. I would prefer to add a 

```bash
cd $GOPATH/src/github.com/coreos/prometheus-operator/contrib/kube-prometheus
```

As the first command. What do you think?

**Comment by brancz** [comment]
```
cd contrib/kube-prometheus/
```
works for me as well

**Comment by stroebitzer** [comment]
Sounds great ;)

**Comment by brancz** [comment]
lgtm, thanks!

**Pull request merged**
