### PR TITLE
pkg/prometheus: add podTargetLabels to CRD for sourcing additional labels from pods

### PR DESCRIPTION
**Pull request by crandles**
Something like this was suggested in #1604 for promoting pod labels like service labels are via `targetLabels`.

### CODE REVIEW

**Comment by crandles** [comment]
Will do

**Comment by crandles** [comment]
Added a test for PodTargetLabels as well as TargetLabels, since they are pretty similar.

**Comment by crandles** [comment]
I can't tell why this test is failing. I tried to regen docs, but there were no changes.

**Comment by brancz** [comment]
You need to rebase and then re-generate. Sorry recent merges caused a conflict.

**Comment by brancz** [comment]
lgtm

**Pull request merged**
