### PR TITLE
Upgrade prometheus-adapter APIService to v1

### PR DESCRIPTION
**Pull request by mgoodness**
`APIRegistration` went v1 in Kubernetes v1.10. Upgrading seems safe.

Also:

- remove unnecessary namespace from prometheus-adapter ClusterRoleBinding
- update Grafana dashboardDefinitions (side effect of `jb update`)

Signed-off-by: Michael Goodness <mike.goodness@ticketmaster.com>

### CODE REVIEW

**Comment by brancz** [comment]
Generally this sounds and looks good to me.

I think some jsonnet deps were outdated, can you just run `make clean generate-in-docker` from the root of the repo once more? Thanks!

**Comment by mgoodness** [comment]
Dunno what's going on with the build, but I'm happy to help if I can.

**Comment by brancz** [comment]
My apologies, this is an artifact of us having a dependency on our own repo. You need to run `make clean generate-in-docker` and then commit all of that into (yet another) new commit. This is because the jsonnet dependency then points at the "last" commit, so amending or rebasing gives the commit a new commit id.

**Comment by mgoodness** [comment]
Not your fault; I'd previously appended, not realizing the self-dependency. I'll do things the right way going forward. Have a few more kustomize-related things in mind.

**Comment by brancz** [comment]
This lgtm :+1: thanks!

**Pull request merged**
