### PR TITLE
kube-prometheus: put in kube-system

### PR DESCRIPTION
**Pull request by philips**
These manifests should live in kube-system; otherwise the label selector
won't work.

### CODE REVIEW

**Comment by brancz** [comment]
So far this was solved by setting the namespace when calling kubectl, but as these manifests always have to be in kube-system namespace this makes sense. :+1: lgtm

**Comment by brancz** [comment]
Can you just run `make docs`? It embeds the yaml files into our docs, we make sure our docs are up to date with the manifests this way.

**Comment by jonboulle** [comment]
> BIN  contrib/.DS_Store

remove this

**Comment by fabxc** [comment]
I'll remove it along with a later commit.

**Pull request merged**
