### PR TITLE
#669: Use /-/healthy and /-/ready for probes

### PR DESCRIPTION
**Pull request by julianvmodesto**
Addresses #669

### CODE REVIEW

**Comment by brancz** [comment]
this generally lgtm

@coreosbot test this please

**Comment by julianvmodesto** [comment]
Oops, looks like a fail, how do i figure out what the failure is? I'll try running the e2e tests on minikube too.

**Comment by brancz** [comment]
The test cluster didn't come up in time, so we'll just have to re-run this.

@coreosbot test this please

**Comment by brancz** [comment]
due to some problems with the build infra I'm testing this manually, I'll report on how it goes

**Comment by brancz** [comment]
Ran the tests myself, and it's all green. lgtm :+1: thanks a lot for your contribution!

**Pull request merged**
