### PR TITLE
Add role rules permissions to get metrics from kubelet

### PR DESCRIPTION
**Pull request by luisyonaldo**
Fixes https://github.com/coreos/prometheus-operator/issues/867

### CODE REVIEW

**Comment by brancz** [comment]
Thanks @luisyonaldo! Could you add this [here](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-roles.yaml#L49-L51) as well and run `make generate` in the root of the repo? Thanks!

**Comment by luisyonaldo** [comment]
nothing change after `make generate`, is that the expected behaviour?

**Comment by luisyonaldo** [comment]
also, on which doc should be stated that `kubelet` must be running with `--authentication-token-webhook` and `--authorization-mode=Webhook` options?

**Comment by brancz** [comment]
I felt like the file is used to generate some content, but CI will tell us whether that's true or not :slightly_smiling_face: if you say so then CI should be green and then this would be good to merge for me.

**Comment by luisyonaldo** [comment]
looks like the file is not being used to generate something

**Comment by brancz** [comment]
Perfect, thanks!

**Pull request merged**
