### PR TITLE
prometheus rule validator: add full PrometheusRule unmarshal step

### LINKED ISSUE #2727: Bad PrometheusRule prevented prometheus operator from starting
The prometheus operator was failing to start with the following error:

```
msg="Unhandled error received. Exiting..." 
err="creating CRDs failed: waiting for PrometheusRule crd failed: timed out waiting for Custom Resource: failed to list CRD: v1.PrometheusRuleList.Items: []*v1.PrometheusRule: v1.PrometheusRule.Spec: v1.PrometheusRuleSpec.Groups: []v1.RuleGroup: v1.RuleGroup.Rules: []v1.Rule: v1.Rule.Annotations: ReadString: expects \" or n, but found f, error found in #10 byte of ...|summary\":false},\"exp|..., bigger context ...|un successfully in the last 24 hours.\",\"summary\":false},\"expr\":\"job:last_success:hours_ago{ exported|..."
```

This turned out to be a problem with the following rule:

```
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
...
spec:
  groups:
    - name: fakerule.rules
      rules:
        - alert: SomeAlert
          expr: someexpression > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: No
            description: some alert
```

The problem part of this is the "summary: No". No is special in yaml and will be resolved as a boolean that is false.

Now granted this is bad config, but the operator should deal with this better.

- The operator should log the namespace and path for the invalid crd in the error message.
- A bad prometheusrule should not prevent the operator from starting. Invalid rules should just be skipped over.
- The operator should update a "status" field on the crd to inform the user that their prometheusrule has been rejected and why.
- The operator should expose a metric to prometheus to show failing rules.

### PR DESCRIPTION
**Pull request by allen13**
Fix prometheus rule validator admitting rules with invalid label types.

Fixes #2727,#2962

### CODE REVIEW

**Comment by brancz** [comment]
Failing test seems correctly failing, but otherwise happy with this. Thank you for working on this!

**Comment by allen13** [comment]
Investigating why this is failing in the travis ci environment. 
`make test-unit` and `go test -timeout 30s github.com/coreos/prometheus-operator/pkg/admission -run ^(TestAdmitBadRuleWithBooleanInAnnotations)$` are working locally. Suspect it may be differences between go 1.12 and 1.13

**Comment by allen13** [comment]
Confirmed that the tests pass when built with go1.13.8 in travis. Must be something to do with Unmarshal in 1.12.

**Comment by brancz** [comment]
Almost there, now just needs a  `go mod tidy` and `go mod vendor` (with go 1.13 as mods changed slightly).

**Comment by allen13** [comment]
Thanks for the feedback @brancz ! That seems to have done the trick.

**Comment by brancz** [comment]
Thanks a lot for taking care of this! Lgtm

**Pull request merged**
