### PR TITLE
kube-prometheus: Allow skipping etcd TLS errors

### LINKED ISSUE #1755: kube-prometheus: re-introduce insecureSkipVerify for etcd monitoring
I'm creating this issue per [this comment on a recent PR](https://github.com/coreos/prometheus-operator/pull/1732/files#r207700772).

Note that the `insecureSkipVerify` option existed in [v19](https://github.com/coreos/prometheus-operator/blob/v0.19.0/contrib/kube-prometheus/docs/Monitoring%20external%20etcd.md#step-2---create-the-service-endpoints-and-servicemonitor), but in a recent release was deleted.

The reason why `insecureSkipVerify` is needed is described in the comments on issue #1743.

### PR DESCRIPTION
**Pull request by brancz**
Closes #1755 

@mxinden @squat @s-urbaniak

cc @jolson490

### CODE REVIEW

**Comment by jolson490** [comment]
Thank you @brancz for the PR.

Can you please further revise the code in this `kube-prometheus-static-etcd.libsonnet` file so that the user of kube-prometheus is required to specify either `serverName ` or `insecureSkipVerify `? (i.e. specify exactly 1 of the 2 of them.)

e.g. if I have the following in my jsonnet file:
```
local kp =
...
  (import 'kube-prometheus/kube-prometheus-static-etcd.libsonnet') +
  {
    _config+:: {
      namespace: 'monitoring',
      etcd+:: {
        ips: ['192.168.213.212','192.168.213.171','192.168.213.210'],

        clientCA: importstr 'ca.pem',
        clientCert: importstr 'etcd.pem',
        clientKey: importstr 'etcd-key.pem',

        //serverName: '127.0.0.1',
        insecureSkipVerify: true,
      },
...
```

then running `build.sh` yields:
```
josh@MyMac$ egrep "serverName|insecureSkipVerify" manifests/prometheus-serviceMonitorEtcd.yaml
      insecureSkipVerify: true
      serverName: null
```

and then when I run `kubectl create -f manifests/` I get the following:
```
The ServiceMonitor "etcd" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"monitoring.coreos.com/v1", "kind":"ServiceMonitor", "metadata":map[string]interface {}{"labels":map[string]interface {}{"k8s-app":"etcd"}, "name":"etcd", "namespace":"kube-system", "creationTimestamp":"2018-08-06T22:07:19Z", "uid":"162f808d-99c5-11e8-991f-080027ef95e6", "selfLink":"", "clusterName":""}, "spec":map[string]interface {}{"endpoints":[]interface {}{map[string]interface {}{"port":"metrics", "scheme":"https", "tlsConfig":map[string]interface {}{"insecureSkipVerify":true, "keyFile":"/etc/prometheus/secrets/kube-etcd-client-certs/etcd-client.key", "serverName":interface {}(nil), "caFile":"/etc/prometheus/secrets/kube-etcd-client-certs/etcd-client-ca.crt", "certFile":"/etc/prometheus/secrets/kube-etcd-client-certs/etcd-client.crt"}, "interval":"30s"}}, "jobLabel":"k8s-app", "selector":map[string]interface {}{"matchLabels":map[string]interface {}{"k8s-app":"etcd"}}}}: validation failure list:
spec.endpoints.tlsConfig.serverName in body must be of type string: "null"
```

Though I suppose I could workaround this by specifying any dummy string value for `serverName` (when I specify `insecureSkipVerify: true`).

(By the way, I'll update the relevant commentary in #1732 accordingly per whatever the outcome of this PR ends up being.)

**Comment by brancz** [comment]
@jolson490 thanks for trying it out. I just pushed an update which doesn't render `serverName` if it's unset. Could you try again? Thanks! :slightly_smiling_face:

**Comment by jolson490** [comment]
Thanks for the additional update Frederic - that is better.

I'm not trying to be picky, but the only gotcha at this point is: if someone specifies neither `serverName` nor `insecureSkipVerify`, then in `manifests/prometheus-serviceMonitorEtcd.yaml` they'll get `insecureSkipVerify: false` and `serverName` won't be set - which will lead to authentication errors on the `/targets` page with their etcd targets.

I'm barely a newbie at jsonnet - I don't know how feasible it is to make it required to specify a value for exactly 1 of 2 different variables. At this point if you wanna call the code in `kube-prometheus-static-etcd.libsonnet` good enough then I'd be happy to add commentary (to [examples/etcd.jsonnet](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/examples/etcd.jsonnet) via PR #1732) to tell users when/how to set one/both of these 2 variables.

By the way, thanks for adding `examples/etcd-skip-verify.jsonnet`, but just IMHO I think it's sufficient that we already have a (rather all encompassing) etcd jsonnet example (i.e. the aforementioned `examples/etcd.jsonnet`).

**Comment by brancz** [comment]
Not being picky at all, we want to be precise, so I appreciate the feedback! You’re right, and jsonnet gives us that ability, so let’s make sure we don’t set it if it’s not specified by a user. Do note though that false is even when unspecified the default value in prometheus and the Prometheus operator.

**Comment by jolson490** [comment]
LGTM

**Pull request merged**
