### PR TITLE
pkg/prometheus: Allow configuration of relabel_configs per ServiceMonitor

### PR DESCRIPTION
**Pull request by crandles**
I need access to various kubernetes meta labels (container name, node name, etc), more than just pod or service labels.

### CODE REVIEW

**Comment by crandles** [comment]
Should be resolved now.

**Comment by brancz** [comment]
Thanks for the contribution! lgtm :+1:

**Comment by atopuzov** [comment]
Thank you for this!

**Comment by shahaf600** [comment]
Hi,
I deployed this servicemonitor and it didn't create the relabel configs:
```apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: nvidia-metrics-prometheus-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  jobLabel: nvidia-metrics-prometheus-exporter
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: nvidia-exporter
  relabelconfigs:
  - sourceLabels:
    - __meta_kubernetes_pod_node_name
    targetLabel: pod_node_name```

**Comment by squat** [comment]
@shahaf600 it looks like your configuration is incorrect. The correct field name is `relabelings` [0]. This should be nested inside of the endpoint object. Also, please open up a new issue if you're need help :)

[0] https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1/types.go#L507

**Comment by shahaf600** [comment]
okay i'll try that, thank you!
btw I thought it's related so I commented here.

**Comment by squat** [comment]
@shahaf600 great! a new issue is just more convenient to encapsulate and track an entire question/problem including manifests, configuration, logs etc. Please don't hesitate to do so!

**Comment by shahaf600** [comment]
@squat btw it worked perfectly for me! thank you!

**Pull request merged**
