### PR TITLE
use the latest version of prometheus in compatibility matrix as default

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

Use the latest version of Prometheus in compatibility matrix instead of v2.7.1

### CODE REVIEW

**Comment by brancz** [comment]
Could you run `make --always-make format generate-in-docker` and commit your changes? That should make the first CI job pass.

**Comment by yeya24** [comment]
I am sorry I have no idea about how to fix this e2e test.
```
FAIL: TestAllNS/y/PromArbitraryFSAcc/allowed-tls-file (307.18s)
                prometheus_test.go:1981: waiting for targets timed out. 0 of 1 targets found. timed out waiting for the condition
```

**Comment by brancz** [comment]
I re-triggered CI but it appears to be failing consistently. Could you try running the tests locally and see if you can figure out what's happening?

**Comment by brancz** [comment]
@pgier could you check out what went wrong here because this seems odd and we intend to ship this version of prometheus so it would be nice to validate that this works :)

**Pull request closed without merging**
