### PR TITLE
Switch from apps/v1beta to apps/v1

### PR DESCRIPTION
**Pull request by mm4tt**
Ref. https://github.com/coreos/prometheus-operator/issues/2592

### CODE REVIEW

**Comment by metalmatze** [comment]
Thanks for updating this.
I was about to create my PR but happy to take yours. :tada:

**Comment by mm4tt** [comment]
Thanks, @metalmatze!

Any idea about when we can expect this change to be released?

**Comment by metalmatze** [comment]
With a few other people asking about a new release. I think we can try to get something out next week before KubeCon. But no promises. :wink:

**Comment by mm4tt** [comment]
Great news, thanks!

**Pull request merged**
