### PR TITLE
kube-prometheus: regenerate

### LINKED ISSUE #2303: node_exporter: error: unknown long flag '--path.rootfs'
**What did you do?**
 Deployed prometheus operator using /contrib/kube-prometheus/manifests

**What did you see?**
The node-exporters all go into a crash loop and the container is logging the following error:
`node_exporter: error: unknown long flag '--path.rootfs', try --help`

**Environment**
Bare metal

* Prometheus Operator version:
0714fe498018819fa790fc040319210d00e46e7b

* Kubernetes version information:
1.13.1

* Kubernetes cluster kind: 
Kubeadm

* Manifest:
https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml

**Temporary Resolution:**
I resolved this by commenting the following line in the node-exporter-daemonset.yaml:
`- --path.rootfs=/host/root`

Node exporter now successfully runs although I don't know what the net effect of this change is yet.

### PR DESCRIPTION
**Pull request by s-urbaniak**
cc @brancz @metalmatze

Closes #2303

### CODE REVIEW

**Comment by brancz** [comment]
lgtm on green

**Comment by metalmatze** [comment]
Sorry, I think I told you to ./build.sh from `contrib/kube-prometheus` when doing this earlier. You actually need to run `make generate` from the root to generate the docs too.
Somehow the generator for the alertmanager.crd.yaml changed. Not sure if this will be fixed with the previous command too.
https://travis-ci.org/coreos/prometheus-operator/jobs/480414890#L1759

**Comment by s-urbaniak** [comment]
@metalmatze i'll try

**Comment by s-urbaniak** [comment]
@metalmatze ok, this looks like more changes now, let's see how CI behaves ;-)

**Comment by metalmatze** [comment]
Thank you so much for working through this @s-urbaniak! :+1:

**Pull request merged**
