### PR TITLE
kube-prometheus: Add possibility to set compute resources

### PR DESCRIPTION
**Pull request by y-batsianouski**
Hello!

I've added the possibility to configure resource requests and limits for prometheus-operator, prometheus, alertmanager and node-exporter.

### CODE REVIEW

**Comment by brancz** [comment]
I'm not sure I feel these configurations are necessary. Why can't we make use of jsonnet features and just merge these on top of a setup?

**Comment by y-batsianouski** [comment]
I faced problems with node-exporter and kube-state-metrics (Because their containers in array and there is no straight-forward way to add container resources for somebody who haven't deep knowlege with jsonnet). But I already find the solution. 

Anyway It will be helpful to have a documentation for that.

**Comment by brancz** [comment]
I think rather than a configuration if we add something I would prefer to have parameterizable patches, so that it would look something like:

```jsonnet
// ... normal kube-prometheus setup
+ kp.kubeStateMetrics.WithKubeStateMetricsResources(...)
```

This way we can keep the config objects small and clean and make modifications explicit downstream thought.

**Comment by metalmatze** [comment]
kube-prometheus just moved to https://github.com/coreos/kube-prometheus. 
See [contrib/kube-prometheus/README.md](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/README.md) for details.

It seems that you made contributions to both projects. Could you create another PR against the new kube-prometheus repository and remove these change from this PR?

Thank you for your contribution and sorry for the inconvenience!

**Comment by paulfantom** [comment]
Closing since project moved.

**Pull request closed without merging**
