### PR TITLE
Update client libraries to Kubernetes 1.13

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
travis-e2e.sh test is timing out. This seems unrelated to this pr.

**Comment by brancz** [comment]
I restarted the job, but lately we've had very little flakes, if the same thing happens I think it'll need a look.

**Comment by squat** [comment]
seems to have failed again. restarting once more. we may need to dig into the failures as other PRs are not flaking this much

**Comment by tamalsaha** [comment]
Looks like something is off.

**Comment by tamalsaha** [comment]
@brancz , sorry it took me a while to research the issue. But the tests are passing now. The problem was that the new k8s.io/klog library requires the glog flags to be explicitly initialized. 

PTAL.

**Comment by brancz** [comment]
lgtm thanks!

**Comment by s-urbaniak** [comment]
@tamalsaha thanks a lot indeed! :+1:

**Pull request merged**
