### PR TITLE
helm: update charts fullname template

### PR DESCRIPTION
**Pull request by luisyonaldo**
fix duplicate naming for resources, like
```
helm install helm/prometheus-operator --name prometheus-operator --namespace monitoring
...

resources:
prometheus-operator-prometheus-operator-...
prometheus-operator-prometheus-operator-...
```
https://github.com/kubernetes/helm/issues/1186

### CODE REVIEW

**Comment by gianrubio** [comment]
@luisyonaldo ci is failling, could you fix that?

**Comment by gianrubio** [comment]
the issue that was causing the CI to fail was fixed, could you rebase it and run again?

**Comment by luisyonaldo** [comment]
@gianrubio it's been fixed, not sure why CI is failing

**Comment by brancz** [comment]
This PR needs a rebase. We had some trouble with our CI setup, sorry for the inconvenience.

**Comment by gianrubio** [comment]
thanks @luisyonaldo

**Pull request merged**
