### PR TITLE
Bump prometheus chart to v2.0

### PR DESCRIPTION
**Pull request by gianrubio**
This is a big PR to update all helm charts, I Bumped all helm componentes to the latest version. 
- prometheus to 2.0.0
- prometheus-operator to 0.15.0
- alertmanager to 0.12.0
- node-exporter to 0.15.1
- kube-state 1.1.0

I also wrote a [python script](https://github.com/gianrubio/prometheus-operator/blob/59421f7018bbeaabbec27631d882b6a7ab521a1d/helm/hack/sync_kube_prometheus.py) to keep kube-prometheus, alerts and dashboards, in sync with with kube-prometheus charts.

### How to test?
```
git clone https://github.com/gianrubio/prometheus-operator/
cd prometheus-operator
git checkout helm-prometheus-2.0
sed -ie 's/    repository/#    repository/g' $(pwd)/helm/*/requirements.yaml
sed -ie 's/#e2e-repository/repository/g' $(pwd)/helm/*/requirements.yaml
helm dep update helm/kube-prometheus 
helm install  --name prometheus-operator helm/prometheus-operator --namespace monitoring  
helm install  --name kube-prometheus helm/kube-prometheus --namespace monitoring  
```

### CODE REVIEW

**Comment by gianrubio** [comment]
After a lot of work all the alert are green and all the dashboards are in sync with kube-prometheus.
Later I'll rebase the commits and review the changes.

screen shot 2017-12-26 at 01 03 29
screen shot 2017-12-26 at 01 04 04

**Comment by gianrubio** [comment]
This PR is ready to merge, can someone review it?

**Comment by nexeck** [comment]
Works for me, tested on k8s 1.8.4 on aws

**Comment by luisyonaldo** [comment]
why did you remove `deployPrometheusOperator` ? I'm waiting this to be able to deploy everything using just `kube-prometheus` chart

**Comment by gianrubio** [comment]
@luisyonaldo there's a race condition between prometheus-operator and kube-prometheus because kube-prometheus needs the prometheus CRD, that's create by the operator, and sometimes takes time to create it. We can work further to add this requirement, maybe using a job to check if the CRD is already created.

**Comment by luisyonaldo** [comment]
good, do you need help or you will add it after merging this?

**Comment by gianrubio** [comment]
of course, PR are always welcome

Giancarlo Rubio

**Comment by joshuacox** [comment]
for whatever reason I had to modify the steps a bit to get it working myself, I ended up sticking it in my [makefile](https://github.com/joshuacox/reactionetes/blob/prometheus-2.0/Makefile#L204-L220) when I finally got it all working.  

```
	$(eval TMP := $(shell mktemp -d --suffix=PROMTMP))
	cd $(TMP) \
		&& git clone https://github.com/gianrubio/prometheus-operator.git
	cd $(TMP)/prometheus-operator \
		&& git checkout helm-prometheus-2.0 \
		&& kubectl apply -f scripts/minikube-rbac.yaml \
		&& bash -c "sed -ie 's/    repository/#    repository/g' $(TMP)/prometheus-operator/helm/*/requirements.yaml" \
		&& bash -c "sed -ie 's/#e2e-repository/repository/g' $(TMP)/prometheus-operator/helm/*/requirements.yaml" \
		&& helm dep update helm/kube-prometheus \
		&& helm install --name prometheus-operator \
			--namespace=$(MONITORING_NAMESPACE) \
			helm/prometheus-operator \
		&& helm install --name kube-prometheus \
			--namespace=$(MONITORING_NAMESPACE) \
			helm/kube-prometheus
```


There are a few successful builds as well at:

[travis](https://travis-ci.org/joshuacox/reactionetes/builds/324597098)

and 

[circleci](https://circleci.com/gh/joshuacox/reactionetes/157)

**Comment by gianrubio** [comment]
@joshuacox what errors you got before adapting your script?

**Comment by joshuacox** [comment]
I wish I saved them all for you, but off of the top of my head:

1. the repo must be added to helm as well `helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/`
1. `minikube-rbac.yaml` must be applied.

**Comment by brancz** [comment]
lgtm, let's solve the last few comments in a follow up

**Comment by gianrubio** [comment]
@joshuacox the PR was merged, can you test in a fresh install and see what happens?
```
$ helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
$ helm install coreos/prometheus-operator --name prometheus-operator
$ helm install coreos/kube-prometheus --name kube-prometheus --set rbacEnable=true 
```

In case you got errors please fill a new issue.

**Comment by joshuacox** [comment]
@gianrubio you bet,

https://circleci.com/gh/joshuacox/reactionetes/172

and 

https://travis-ci.org/joshuacox/reactionetes/builds/325074298

both of those are built using a fresh checked out copy of the `prometheus-operator` repo

**Pull request merged**
