### PR TITLE
Use Go modules with Kubernetes 1.14

### PR DESCRIPTION
**Pull request by metalmatze**
After we merged #2570, I want to give Go modules another shot. Locally this is looking good already. Let's see what our CI says.

Superseeds #2107 

/cc @brancz @mxinden @paulfantom @s-urbaniak @squat

### CODE REVIEW

**Comment by brancz** [comment]
Happy to go ahead with this should CI be happy.

**Comment by brancz** [comment]
cc @simonpasquier as he's done plenty of migrations already and probably knows about 1 or 2 gotchas ;)

**Comment by paulfantom** [comment]
You will also need to make some modifications to `.travis.yml` to make CI happy. I think following are needed:
- remove job executing `golang-dep-ensure.sh`
- add `GO111MODULE=on` env to `.travis.yml`

**Comment by metalmatze** [comment]
Alright. I've vendored all tools necessary to generate our code and configs. Looks like CI is going to be green, if no flakes in e2e tests.

**Comment by metalmatze** [comment]
Any last thoughts? Otherwise I'm going to merge in the next hour.

**Comment by brancz** [comment]
Feel free

**Pull request merged**
