### PR TITLE
Updated helm chart to version v0.20.0

### PR DESCRIPTION
**Pull request by aleerizw**
Updated the clusterrole for the new prometheusrule CRD

### CODE REVIEW

**Comment by aleerizw** [comment]
Ok, I'll take a look at changing the other charts.

**Comment by aleerizw** [comment]
@brancz I don't think the failing test is related

**Comment by gianrubio** [comment]
@aleerizw you can either run `make generate` command or wait for #1447 get merged to rebase your branch

**Comment by brancz** [comment]
CI on master is green again, sorry for the trouble.

**Comment by aleerizw** [comment]
yay it passed

**Pull request merged**
