### PR TITLE
Helm: Allow adding dashboards to grafana via configmaps

### PR DESCRIPTION
**Pull request by Nonymus**
New dashboards can currently be added to grafana via `.Values.serverDashboardFiles`. The variable has to contain files in JSON-Syntax, which are added to Grafana.

With multiple, complex dashboards, your values-file tends to get hard to read, because most lines actually contain json for your dashboards.

When creating a custom helm chart which uses the kube-prometheus chart as dependency, this PR allows you to render configmaps from .json-files (much like the grafana-charts already does for the bundled dashboards) and use them as additional sources for dashboards and datasources.

### CODE REVIEW

**Comment by RyanGordon** [comment]
This is great :+1: Besides the merge conflict, any reasons why this can't be merged?

**Comment by Nonymus** [comment]
Merged master again and resolved conflicts (version bump only).
@gianrubio @brancz Anything else I can do to get this on track?

**Comment by gianrubio** [comment]
thanks @Nonymus

**Comment by naseemkullah** [comment]
Very cool feature!!

Is there any documentation as how to add a custom grafana dashboard as a  config map? I'd really benefit from cross referencing an example to see what the value looks like (is it the path to a configmap file locally, is it the contents of the configmap, does the dashboard json have to be formatted compactly onto 1 line, etc.) This goes for all chart values by the way... I'm not alone with regards to trying to figure out how to apply custom values to a chart.

Many thanks in advance,
N

**Comment by Nonymus** [comment]
@naseemkullah I'll try to come up with a minimal example in a few days, as I'm currently out of town.
In short, you'll have to create a configmap (or multiple) in the same namespace, following the same syntax as the configmap generated by the grafana chart itself. Then, set `serverDashboardConfigmaps` as a list of names of theses additional configmaps.

**Comment by naseemkullah** [comment]
Thank you, in the meantime I've been trying to get it to work, as you can see the deployment for grafana seems to have picked up the `serverDashboardConfirmaps` value (list of 1 item: `custom-grafana`) But I see nothing in the dashboard :(

```
      - args:
        - --watch-dir=/var/grafana-dashboards
        - --grafana-url=http://127.0.0.1:3000
        - --watch-dir=/var/additional-dashboards/custom-grafana
```
```
        volumeMounts:
        - mountPath: /var/grafana-dashboards
          name: grafana-dashboards
        - mountPath: /var/additional-dashboards/custom-grafana
          name: custom-grafana
```
```
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - configMap:
          defaultMode: 420
          name: kube-prometheus-grafana
        name: grafana-dashboards
      - configMap:
          defaultMode: 420
          name: custom-grafana
        name: custom-grafana
```


Also worth mentioning I copied this:
```
        "dashboard": {
            "__inputs": [
                {
                    "description": "",
                    "label": "prometheus",
                    "name": "DS_PROMETHEUS",
                    "pluginId": "prometheus",
                    "pluginName": "Prometheus",
                    "type": "datasource"
                }
            ],
```
and this
```
        "inputs": [
            {
                "name": "DS_PROMETHEUS",
                "pluginId": "prometheus",
                "type": "datasource",
                "value": "prometheus"
            }
        ],
        "overwrite": true
```
at the beggining and end (respectively) of the json dashboard content because I noticed it on the configmap generated by the grafana chart itself. What are those and do we have to add them manually to our custom dashboards every time?

**Comment by matthew-walters** [comment]
I cannot get this to work.
I've created a configmap containing my dashboards, in same namespace, and then install grafana chart, setting value of _serverDashboardConfigmaps_ to be a list containing just the name of this configmap

inside the running grafana-watcher container, 
I can cd into /var/additional-dashboards/my-configmap
and then see my dashboard json files, as expected

but when i check the log for this container,

```
2018/04/25 18:04:07 Initializing dashboards.
2018/04/25 18:04:07 Retrieving existing dashboards
2018/04/25 18:04:07 Deleting 0 dashboards
2018/04/25 18:04:07 Starting...
```

**Comment by Nonymus** [comment]
@naseemkullah Sorry, job kept me busy a while.
Here's the example: [example-kube-prometheus](https://github.com/Nonymus/example-kube-prometheus)

The confusion may be a sign that documentation is needed. There are docs for prometheus-operator and kube-prometheus, but not for the helm charts itself.

Maybe a project member could give a hint if and how a documentation for the helm charts is desired?

**Comment by Nonymus** [comment]
No, it doesn't have to be an extra chart that creates the configmap. It's just the easiest way for me to give an example.

The only thing `dashboard-loader` chart does is creating a configmap named `loader-dashboards` with the contents of `example-dashboard.json`. You can use any other mechanism to create a configmap, doesn't have to be a helm chart.

After the configmap is created, add its name to `grafana.serverDashboardConfigmaps`. In the example, this is done in `values.yaml` by configuring the depended chart. If the `kube-prometheus` chart is installed directly, you can do this in an extra values-file you supply when installing/updating `kube-prometheus`:

```bash
$ cat myvalues.yaml
grafana:
  serverDashboardConfigmaps:
  - loader-dashboards
```
```bash
$ helm install coreos/kube-prometheus --namespace=monitoring --name=kube-prometheus -f myvalues.yaml
```
or 
```bash
$ helm upgrade kube-prometheus coreos/kube-prometheus -f myvalues.yaml
```
respectivly.

**Pull request merged**
