### PR TITLE
add livenessprobe

### LINKED ISSUE #303: Setup livenessProbe
Today my prometheus-k8s stucked and I realised that there's no livenessProbe for most of the objects like operator, alertmanager and some examples. Is this proposital? If is not can I do a PR for fix that?

### PR DESCRIPTION
**Pull request by gianrubio**
I'm very conservative onto failureThreshold to avoid pod restarts. After this PR the generated liveness probe will be

```
 livenessProbe:
  failureThreshold: 10
  httpGet:
    path: /status
    port: web
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10
```

Fix #303

### CODE REVIEW

**Comment by brancz** [comment]
Please test this

**Comment by brancz** [comment]
test this please

**Comment by brancz** [comment]
@mxinden is investigating why tests are not being run, we'll hold off for now and if it turns out we can't fix it quickly I'll test it myself some time tomorrow or the day after.

**Comment by brancz** [comment]
test this please

**Comment by mxinden** [comment]
Test this please.

**Comment by mxinden** [comment]
Test this please.

**Comment by mxinden** [comment]
@brancz @gianrubio PR trigger works again. Sorry for the troubles.

**Comment by brancz** [comment]
@mxinden thanks for fixing the builds, saved me a lot of time. LGTM! Thanks a lot @gianrubio

**Pull request merged**
