### PR TITLE
[helm] bump exporter-kube-state version

### PR DESCRIPTION
**Pull request by redondos**

### CODE REVIEW

**Comment by gianrubio** [comment]
CI is failing, could you fix it?

**Comment by redondos** [comment]
Thanks for the changes, Giancarlo; it looks like Frederic has already upgraded the core images and released 0.17 in 6a5c1204610e8c55ae59a7fda297d41f45c539f6. I'm closing this PR.

**Comment by gianrubio** [comment]
Actually it’s not the same changes, that was only to kube-Prometheus. It’s still required to update the helm charts, do you want to work on it?

**Comment by richerve** [comment]
The reason the CI is failing is because one of the pods is not starting, specifically `exporter-kube-state`. Taking a deeper look running it locally the failing container is not `exporter-kube-state` itself but `exporter-kube-state-addon-resizer` that as I understand is using this: https://github.com/kubernetes/autoscaler/tree/master/addon-resizer

Printing the logs for that container shows:
```ERROR: logging before flag.Parse: I0227 11:15:46.927249       1 pod_nanny.go:64] Invoked by [/pod_nanny --container=exporter-kube-state --cpu=100m --extra-cpu=1m --memory=100Mi --extra-memory=2Mi --threshold=5 --deployment=latest-exporter-kube-state-exporter-kube-state]
ERROR: logging before flag.Parse: I0227 11:15:46.927747       1 pod_nanny.go:76] Watching namespace: default, pod: latest-exporter-kube-state-exporter-kube-state-686f584c55-2hdbj, container: exporter-kube-state.
ERROR: logging before flag.Parse: I0227 11:15:46.928392       1 pod_nanny.go:77] storage: MISSING, extra_storage: 0Gi
ERROR: logging before flag.Parse: I0227 11:15:47.018352       1 pod_nanny.go:162] Failed to read data from config file "MISSING/NannyConfiguration": open MISSING/NannyConfiguration: no such file or directory, using default parameters
ERROR: logging before flag.Parse: I0227 11:15:47.018391       1 pod_nanny.go:166]
ERROR: logging before flag.Parse: I0227 11:15:47.018425       1 pod_nanny.go:101] cpu: , extra_cpu: , memory: , extra_memory:
panic: cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

goroutine 1 [running]:
k8s.io/autoscaler/addon-resizer/vendor/k8s.io/apimachinery/pkg/api/resource.MustParse(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/kawych/go-tools/src/k8s.io/autoscaler/addon-resizer/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:136 +0x253
main.main()
	/usr/local/google/home/kawych/go-tools/src/k8s.io/autoscaler/addon-resizer/nanny/main/pod_nanny.go:108 +0x6d5```

So at first sight it appears that the new version 1.8 requires a config file and/or parameters to work. I'm not familiar to how it works, still researching, but wanted to leave this here if anyone comes with a solution quicker.

**Comment by richerve** [comment]
In version 1.8.0 they completely remove the cpu and memory parameters to use the config file instead. This is the error that I'm getting in 1.8.0:
```
ERROR: logging before flag.Parse: I0227 11:32:35.021835       1 pod_nanny.go:59] Invoked by [/pod_nanny --container=exporter-kube-state --cpu=100m --extra-cpu=1m --memory=100Mi --extra-memory=2Mi --threshold=5 --deployment=exporter-kube-state-18-exporter-kube-state]
unknown flag: --cpu
Usage of /pod_nanny:
      --config-dir string      Path of configuration containing base resource requirements. (default "MISSING")
      --container string       The name of the container to watch. This defaults to the nanny itself. (default "pod-nanny")
      --deployment string      The name of the deployment being monitored. This is required.
      --estimator string       The estimator to use. Currently supported: linear, exponential (default "linear")
      --extra-storage string   The amount of storage to add per node. (default "0Gi")
      --namespace string       The namespace of the ward. This defaults to the nanny pod's own namespace. (default "default")
      --pod string             The name of the pod to watch. This defaults to the nanny's own pod. (default "exporter-kube-state-18-exporter-kube-state-7b54c99db-cjtlc")
      --poll-period int        The time, in milliseconds, to poll the dependent container. (default 10000)
      --storage string         The base storage resource requirement. (default "MISSING")
      --threshold int          A number between 0-100. The dependent's resources are rewritten when they deviate from expected by more than threshold.
```
And in version 1.8.1 (the one the update is proposing), they reintroduce the cpu and memory parameters, but as we can see in the first posted error log, the `cpu`, `extra_cpu`, `memory` and `extra_memory` are empty at the end of the parsing.

**Comment by richerve** [comment]
For now using version "1.7" of `addon-resizer` works, so maybe will be better to update to that version first and create a new issue for the update to v1.8.1

**Comment by richerve** [comment]
Given that the prometheus-operator and almost all other helm Charts are updated in master already, I rebased this PR on that and only applied the update to `exporter-kube-state`. Rephrasing the PR as the last commit message will better reflect this.

**Comment by redondos** [comment]
@gianrubio sorry for the late reply, you beat me to the punch here. I adapted this PR with Ricardo's help, can you let me know if it's good to go or needs any more changes?

**Comment by gianrubio** [comment]
Please rebase it and we are ready to merge!

**Comment by richerve** [comment]
Rebased

**Comment by richerve** [comment]
I can't see why is failing, in this case is a timeout but I don't know why it happens

**Comment by gianrubio** [comment]
for some reason minikube didn't start, I saw some errors on travis or google network `  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0curl: (7) Failed to connect to storage.googleapis.com port 443: Connection timed out`
Please re run the test

**Comment by richerve** [comment]
How can I re-run the test? I can't see a way to do it on the Travis UI

**Comment by redondos** [comment]
I'll re-open the PR to trigger a rebuild.

**Pull request merged**
