### PR TITLE
Add nodeSelector to PrometheusSpec

### PR DESCRIPTION
**Pull request by iterion**
See #107. It seems to me this is all that is necessary. I haven't been able to run the e2e test as I don't currently have a test cluster available.

### CODE REVIEW

**Comment by brancz** [comment]
I'm currently e2e testing this, to see that no existing functionality breaks through these changes. I don't know what could break due tot this, but want to make sure. Other than that have you tested and can confirm that this functionality does indeed work as intended?

**Comment by iterion** [comment]
I haven't been able to test it yet, our clusters are still 1.4. I can spin
up a new test cluster and try it out if that would help?

**Comment by brancz** [comment]
That would be great @iterion !

**Comment by brancz** [comment]
I tested this against the e2e tests, and it looks good, so once you can confirm that this does indeed work we can merge.

**Comment by brancz** [comment]
It seems that recent changes introduced a conflict. Could you maybe rebase?

**Comment by brancz** [comment]
Sorry for all the comments, can you also add documentation as a comment in the struct and in the `Documentation/prometheus.md` file. Thanks! 🙂

**Comment by iterion** [comment]
Will do, I'm on vacation right now but I'll get to it early next week.
Apologies for the delay.

**Comment by brancz** [comment]
We continued this in #121. Thanks a lot for your head start @iterion ! 🎉

**Comment by iterion** [comment]
Awesome, thanks!

**Pull request closed without merging**
