### PR TITLE
Add security recommendations for ingress

### PR DESCRIPTION
**Pull request by gianrubio**
This PR add grafana as ingress service. It also add some advice on how to protect this resources over internet.

### CODE REVIEW

**Comment by galexrt** [comment]
@gianrubio Do you know for what ingresses the `whitelist-source-range` annotation works for?

**Comment by brancz** [comment]
I think it's very confusing to have a manifest mentioning grafana when the document is called "Exposing Prometheus and Alertmanager". I'm all for the security aspect of this PR, but I think we should leave out grafana in this document as it would be very confusing to users, because nothing else in the Documentation ever mentions grafana. We will have dedicated docs for grafana once we do implement the grafana TPR, until then I would like to keep everything Prometheus and Alertmanager scoped in the docs for the operator. Main reason being these docs are now published on coreos.com. https://coreos.com/operators/prometheus/docs/latest/

**Comment by gianrubio** [comment]
> @gianrubio Do you know for what ingresses the whitelist-source-range annotation works for? (Maybe worth noting if it will only work for certain ingress providers)

@galexrt not yet, https://github.com/kubernetes/ingress/issues/566

@brancz got it, shall I keep only the security recommendation and remove the grafana expose?

**Comment by brancz** [comment]
> shall I keep only the security recommendation and remove the grafana expose?

That sounds perfect. :+1:

**Comment by gianrubio** [comment]
@brancz done!

**Comment by brancz** [comment]
Awesome! Thanks a lot! :tada:

**Pull request merged**
