### PR TITLE
Fix k8s labels in prometheus rules

### PR DESCRIPTION
**Pull request by paskal**
Fix https://github.com/helm/charts/issues/9034, replacements list:
```
{{ $labels.job }} -> {{ $labels. job_name }}
{{ $labels.namespaces }} -> {{ $labels.namespace }}
```

### CODE REVIEW

**Comment by brancz** [comment]
These alerts are not defined in this repository, they are just a dependency that happens to be used here, therefore this needs to be fixed here first: https://github.com/kubernetes-monitoring/kubernetes-mixin

**Comment by paskal** [comment]
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/115 created. Should this one be closed, will you import changes from upstream automatically?

**Comment by brancz** [comment]
Once https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/115 is merged we'll still need an update of the dependency here, so we can leave this open :slightly_smiling_face: .

**Comment by brancz** [comment]
to make sure everything is generated as wanted and to bump the dependency do the following steps:

* run `jb update` in the `contrib/kube-prometheus/` directory
* commit the changes created
* run `make generate-in-docker` in the root of the repo
* commit the changes created
* push :slightly_smiling_face:

**Comment by brancz** [comment]
lgtm :+1: thanks a lot for the effort!

**Pull request merged**
