### PR TITLE
pkg/client/monitoring/v1alpha1: use pointer for status

### PR DESCRIPTION
**Pull request by brancz**
I haven't added a test as a unit test would be testing the transformation of a faked http request. I would have wanted to add an end-to-end test, but as the operator is not exposed in any way it's not really possible to issue requests against it right now. Do you think it is worth exposing?

Either way, I tested this manually and have verified that this works.

@alexsomesan @fabxc

### CODE REVIEW

**Comment by fabxc** [comment]
As we now went with just using the package function rather than the HTTP endpoint, I don't think it has high priority now.

**Comment by fabxc** [comment]
Can we also add the `Paused` field to the status and add it to the `PrometheusStatus` function while we are at it?

**Comment by brancz** [comment]
Updated @fabxc

**Comment by fabxc** [comment]
👍

**Pull request merged**
