### PR TITLE
Fix Crashlooping panels in Grafana dashboards

### PR DESCRIPTION
**Pull request by Wenzil**
`exporter-kube-state` exposes a `kube_pod_container_status_restarts_total` metric, but the `Crashlooping Pods` and `Crashlooping Control Plane Pods` panels in the `Kubernetes Cluster Health` and `Kubernetes Cluster Status` dashboards mistakenly query `kube_pod_container_status_restarts` instead.

This PR fixes that

### CODE REVIEW

**Comment by gianrubio** [comment]
@brancz should this changed be applied in kube-prometheus before applying in helm?

**Comment by brancz** [comment]
It's a bit more complicated than that, so I would recommend just moving forward with this. We'll take care of syncing the kube-prometheus ones.

**Comment by gianrubio** [comment]
@Wenzil please fix the CI, you forgot to[ bump the version](https://github.com/coreos/prometheus-operator/tree/master/helm#how-to-contribue) of the charts

**Comment by Wenzil** [comment]
CI is fixed :)

**Comment by gianrubio** [comment]
thanks @Wenzil

**Pull request merged**
