### PR TITLE
Target name relabeling

### PR DESCRIPTION
**Pull request by mkabischev**
This PR implements solution to relabel `__meta_kubernetes_endpoint_address_target_name ` to `pod`/`node` label proposed in #1548.

### CODE REVIEW

**Comment by brancz** [comment]
Thank you so much for this! Did you already try whether kubelet's would be tagged with the `node` label?

**Comment by brancz** [comment]
Also I'm not entirely sure the Pod part is actually necessary as we already do that kind of a relabelling rule.

**Comment by mkabischev** [comment]
@brancz, yeah, I've tested it :)
screen shot 2018-09-17 at 16 56 05

I removed old relabelling for pod, so now they works the same way.

**Comment by brancz** [comment]
Really awesome! Thanks a lot!

> I removed old relabelling for pod, so now they works the same way.

Whoops, I missed that.

lgtm :+1: 

(still giving others a chance to review)

**Pull request merged**
