### PR TITLE
scripts/jsonnet/Dockerfile: re-enable python-yaml

### PR DESCRIPTION
**Pull request by s-urbaniak**
... as it was removed https://github.com/coreos/prometheus-operator/pull/2739.

### CODE REVIEW

**Comment by paulfantom** [comment]
lgtm

**Comment by paulfantom** [comment]
merging without travis tests as this is not covered by them.

**Comment by kakkoyun** [comment]
@s-urbaniak My bad, sorry for the inconvenience.

**Comment by s-urbaniak** [comment]
@kakkoyun no worries at all!

**Comment by metalmatze** [comment]
Interesting. Why do we need this?

**Comment by s-urbaniak** [comment]
@metalmatze currently, cluster-monitoring-operator is using this image and is blocked by not having `yaml` as it is used here: https://github.com/openshift/cluster-monitoring-operator/blob/e77c86ab579f96589bf294c10878dc9f575bb82e/hack/merge_cluster_roles.py#L20

**Comment by metalmatze** [comment]
That's the file I was looking for. Wasn't aware of the python file. Thanks for the pointer!

**Comment by s-urbaniak** [comment]
suggestion: we could/should factor the above as a Go program, thus reducing dependencies.

**Pull request merged**
