### PR TITLE
Add keepOriginalDashboards and keepOriginalDatasources to Grafana helm chart

### PR DESCRIPTION
**Pull request by MattiasGees**
This adds two new values to the Grafana HELM chart. When defining custom datasources and/or dashboards, it is possible to also keep the original defined datasources and dashboards. This is handy if you want to extend Grafana but still want to enjoy the original ones.

At this moment this will be a breaking change for people using custom dashboards. If you want, I can change the if/else structure to keep backwards compatibility.

### CODE REVIEW

**Comment by MattiasGees** [comment]
@gianrubio is there any interest in this?

**Comment by gianrubio** [comment]
please wait until I merge #1006

**Comment by gianrubio** [comment]
could you check why CI is failling?

**Comment by MattiasGees** [comment]
@gianrubio The error in CI states the following
```
echo 'ERROR: Some containers failed to reach the ready state'
```

From the looks of it `kube-prometheus-exporter-kube-state` is having problems:
```
kube-prometheus-exporter-kube-state-75b4b85655-527d4   2/2       Terminating   0         10m
```

I haven't touched that exporter. So I think a temp hick-up, maybe restarting travis build will fix it?

**Comment by gianrubio** [comment]
I don't have permission to restart CI you could send a forced push to run the CI again

**Comment by brancz** [comment]
Restarted.

**Comment by MattiasGees** [comment]
Now it went through the `e2e` test but it shows canceled in the `deploy`.

**Comment by gianrubio** [comment]
Lgtm on green!

**Comment by gianrubio** [comment]
thanks @MattiasGees

**Pull request merged**
