### PR TITLE
Minor typo fix

### PR DESCRIPTION
**Pull request by ScottBrenner**
is was -> was

### CODE REVIEW

**Comment by brancz** [comment]
Could you run `make generate` in the root of the repo or in `contrib/kube-prometheus/`. The rule files are bin-packed into a `ConfigMap`.

**Comment by mxinden** [comment]
@ScottBrenner friendly ping :)

**Comment by ScottBrenner** [comment]
Sorry for the delay - afraid I'm having some Windows 10/Docker issues currently, can't run `make generate`.

**Comment by mxinden** [comment]
Replacement PR: https://github.com/coreos/prometheus-operator/pull/950

Thanks for the hint @ScottBrenner.

**Pull request closed without merging**
