### PR TITLE
adding examples for kube-aws

### PR DESCRIPTION
**Pull request by VinceMD**
simple examples for kube-aws. Just the services to monitor kube-controller-manager and kube-scheduler.

### CODE REVIEW

**Comment by brancz** [comment]
Could you just run `jb update` in the `contrib/kube-prometheus/` repo and commit the changes that appear into a new commit? Then CI should pass.

**Comment by VinceMD** [comment]
@brancz I just did jb update but it didn't change anything locally so nothing to push. Not sure what to do

**Comment by brancz** [comment]
The jsonnet snippets in that folder are tested to see if they build correctly, CI is failing, because CI is not using head of your PR. Just run `jb update` in the `contrib/kube-prometheus/` directory and commit the result to a new commit.

**Comment by VinceMD** [comment]
```jb update
Cloning into 'vendor/.tmp/jsonnetpkg-kube-prometheus-.938032211'...
done.
Checking out files: 100% (6882/6882), done.
Cloning into 'vendor/.tmp/jsonnetpkg-ksonnet-master762567574'...
remote: Enumerating objects: 2500, done.
remote: Total 2500 (delta 0), reused 0 (delta 0), pack-reused 2500
Receiving objects: 100% (2500/2500), 1.97 MiB | 319.00 KiB/s, done.
Resolving deltas: 100% (939/939), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Cloning into 'vendor/.tmp/jsonnetpkg-kubernetes-mixin-master645193213'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 667 (delta 3), reused 8 (delta 3), pack-reused 655
Receiving objects: 100% (667/667), 4.96 MiB | 839.00 KiB/s, done.
Resolving deltas: 100% (399/399), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Cloning into 'vendor/.tmp/jsonnetpkg-grafonnet-master854277432'...
remote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 1376 (delta 44), reused 62 (delta 27), pack-reused 1289
Receiving objects: 100% (1376/1376), 811.27 KiB | 288.00 KiB/s, done.
Resolving deltas: 100% (795/795), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Cloning into 'vendor/.tmp/jsonnetpkg-grafana-builder-master103446839'...
remote: Enumerating objects: 72, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 4823 (delta 45), reused 64 (delta 40), pack-reused 4751
Receiving objects: 100% (4823/4823), 13.41 MiB | 1.94 MiB/s, done.
Resolving deltas: 100% (1390/1390), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Cloning into 'vendor/.tmp/jsonnetpkg-grafana-master077794602'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 440 (delta 6), reused 16 (delta 6), pack-reused 419
Receiving objects: 100% (440/440), 118.45 KiB | 0 bytes/s, done.
Resolving deltas: 100% (196/196), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Cloning into 'vendor/.tmp/jsonnetpkg-grafonnet-master104791169'...
remote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 1376 (delta 44), reused 62 (delta 27), pack-reused 1289
Receiving objects: 100% (1376/1376), 811.27 KiB | 315.00 KiB/s, done.
Resolving deltas: 100% (795/795), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Cloning into 'vendor/.tmp/jsonnetpkg-ksonnet-master531193324'...
remote: Enumerating objects: 2500, done.
remote: Total 2500 (delta 0), reused 0 (delta 0), pack-reused 2500
Receiving objects: 100% (2500/2500), 1.97 MiB | 400.00 KiB/s, done.
Resolving deltas: 100% (939/939), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Cloning into 'vendor/.tmp/jsonnetpkg-prometheus-operator-v0.25.0513178203'...
remote: Enumerating objects: 104, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 39202 (delta 40), reused 62 (delta 22), pack-reused 39098
Receiving objects: 100% (39202/39202), 53.41 MiB | 2.71 MiB/s, done.
Resolving deltas: 100% (21871/21871), done.
Checking out files: 100% (6885/6885), done.
Note: checking out 'v0.25.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 82a6ad2... Merge pull request #2043 from mxinden/cut-v0.25.0
Cloning into 'vendor/.tmp/jsonnetpkg-ksonnet-master521055742'...
remote: Enumerating objects: 2500, done.
remote: Total 2500 (delta 0), reused 0 (delta 0), pack-reused 2500
Receiving objects: 100% (2500/2500), 1.97 MiB | 337.00 KiB/s, done.
Resolving deltas: 100% (939/939), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Cloning into 'vendor/.tmp/jsonnetpkg-etcd-mixin-master806971717'...
remote: Enumerating objects: 84824, done.
remote: Total 84824 (delta 0), reused 0 (delta 0), pack-reused 84824
Receiving objects: 100% (84824/84824), 45.27 MiB | 3.25 MiB/s, done.
Resolving deltas: 100% (54323/54323), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
```

```
ALT-C1MQQ4X5G944:kube-prometheus vincentbrouillet$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   jsonnetfile.lock.json

no changes added to commit (use "git add" and/or "git commit -a")

No change apart from jsonnetfile.lock.json. Should I commit jsonnetfile.lock.json ?

**Comment by VinceMD** [comment]
ok, got you. Now there is a conflict

**Comment by brancz** [comment]
Sorry about all of this, I understand it must have been frustrating, I quickly rebased and resolved the conflicts, I think it should be good now, let's see what CI thinks :slightly_smiling_face: .

**Comment by brancz** [comment]
Looks like it worked. Thanks for your work, highly appreciated! :slightly_smiling_face: :+1:

**Comment by VinceMD** [comment]
no frustration, just learnings. Thanks

**Pull request merged**
