### PR TITLE
add make helm-init-repo command to initialize the helm repo 

### PR DESCRIPTION
**Pull request by ant31**
Move all exporters to the helm root folder
Add make helm-init-repo command to initialize the helm repo

from #676

### CODE REVIEW

**Comment by ant31** [comment]
cc @gianrubio

**Comment by brancz** [comment]
@gianrubio we finally got to this, and @ant31 pushed an initial set of charts to the bucket. Once you give a lgtm on this, we are happy to merge this.

**Comment by ant31** [comment]
The only modification is on the Makefile: only one command to run: `helm-packages`, order pushes, and update dep for `kube-prometheus`

**Comment by gianrubio** [comment]
The changes are fine, I'm wondering when we're going to trigger the `make helm-package` command?
After every change on the helm directory we should trigger this command to update the packages.

**Comment by ant31** [comment]
We can run it from travis on master branch only or per release.

**Comment by brancz** [comment]
I think the helm charts are versioned completely separately.

**Comment by gianrubio** [comment]
I'm working to support prometheus 2.0 on helm so I'll submit the modification to always update the charts when the master branch is merged. Does travis already has aws credentials configured?

**Comment by brancz** [comment]
> Does travis already has aws credentials configured?

Not yet, but I'm happy to add this if we can figure out a reasonable automation strategy.

**Comment by brancz** [comment]
> I'm working to support prometheus 2.0 on helm so I'll submit the modification to always update the charts when the master branch is merged.

This sounds great. If you have suggestions on how we can keep the helm charts somewhat up to date with the kube-prometheus manifests, I'm happy to discuss ideas :slightly_smiling_face:

**Comment by gianrubio** [comment]
let's continue the discussion on #592

**Pull request merged**
