### PR TITLE
v0.23.2 back to master

### PR DESCRIPTION
**Pull request by mxinden**

### CODE REVIEW

**Comment by mxinden** [comment]
As the last _back-to-master_ PR was a cherry-pick, the original commit is again included here.

Let me know if you prefer a rebase instead, omitting that _cut v0.23.1_ commit.

**Comment by brancz** [comment]
no all good like this. lgtm

**Comment by squat** [comment]
dang, looks like something is broken in the generation: https://travis-ci.org/coreos/prometheus-operator/jobs/419648574#L2013-L2014

**Comment by brancz** [comment]
@mxinden I think we just need to run formatting of the go code on top of this.

**Pull request merged**
