### PR TITLE
Add the possibility to mount grafana config

### PR DESCRIPTION
**Pull request by abelgana**
This change enable Grafna config customization.

### CODE REVIEW

**Comment by brancz** [comment]
I would expect that there would be a field to specify the "custom" Grafana config.

**Comment by abelgana** [comment]
@brancz Thanks for the feedback. I think it’s easier to just provide a way of mounting the config folder. By default grafana will look at /etc/grafana for the config file (grafana.ini). The idea is to use the same folder for other configuration files like ldap. I am open to work on improving it.

**Comment by abelgana** [comment]
Hi,

The pipeline is green. Is there something I can in order to merge the PR?

**Comment by gianrubio** [comment]
@abelgana could you rebase it?

**Comment by abelgana** [comment]
@gianrubio 
I will do it later today. Thanks

**Comment by abelgana** [comment]
Should be ok now to merge. The pipeline is green.

**Pull request merged**
