### PR TITLE
Doc typo

### PR DESCRIPTION
**Pull request by jfchevrette**
This is SHA for Alertmanager image, not Thanos

### CODE REVIEW

**Comment by metalmatze** [comment]
Can you please run `make generate` in the root of this repository on your machine? The documentation needs to be updated accordingly.

**Comment by jfchevrette** [comment]
@metalmatze Thanks for reminding me I should read contributing docs next time :)

I've generated the docs and amended my last commit with the updated docs.

**Comment by metalmatze** [comment]
Perfect, will merge on green! :+1:

**Comment by squat** [comment]
dang, looks like the build is failing because `pkg/client/monitoring/v1/openapi_generated.go` needs to be generated too

**Comment by jfchevrette** [comment]
@squat I have updated `pkg/client/monitoring/v1/openapi_generated.go` but I had to run openapi-gen manually. I'm not quite sure why but `make generate` would not update it.

There's also a bunch of additional reformating in the diff. Hopefully that is expected?

**Comment by squat** [comment]
@jfchevrette that's odd, the openapi_generated.go file is a dependency of the generate target. It looks like that extra whitespace was not insignificant :( I think it is because you are running an older version of Golang. The best way to fix this is probably to run `make generate-in-docker` to make the build reproducible

**Comment by metalmatze** [comment]
Yep, that's most definitely coming from running an older version than Go 1.11. :relaxed: :wink:

**Comment by jfchevrette** [comment]
I was using go1.10.4. I used `make generate-in-docker` and everything looks good now, I think.

**Comment by squat** [comment]
the tests failed but it seems like a complete flake. I am re-running the tests and will merge on green

**Pull request merged**
