### PR TITLE
add container customization to thanos-ruler

### PR DESCRIPTION
**Pull request by pgier**
Adds the Containers and InitContainers fields to ThanosRuler allowing
customization of the generated StatefulSet/Pod config.

### CODE REVIEW

**Comment by pgier** [comment]
cc @brancz

**Comment by yeya24** [comment]
I think this feature is important for adding sidecar containers to thanos ruler, like adding jager-agent

**Comment by pgier** [comment]
@LiliC It matches the config of the prometheus and alertmanager operators, allows adding sidecar containers as @yeya24 mentioned, and also allows config of any CLI args which don't have explicit fields.  @s-urbaniak had asked me to add this in the original implementation, but for some reason I missed it.

**Comment by LiliC** [comment]
> and also allows config of any CLI args which don't have explicit fields.

yes this is why I asked, if we have some specific args in mind we should add those to the spec, but can be done in a follow up.

**Pull request merged**
