### PR TITLE
Run e2e tests in parallel

### PR DESCRIPTION
**Pull request by gianrubio**
Speed up travis tests running simultaneously e2e tests 

Similar to #791

### CODE REVIEW

**Comment by gianrubio** [comment]
Took the same time to run in parallel or sequential :(

**Comment by brancz** [comment]
right, but they were started at the same time, no?

**Comment by gianrubio** [comment]
Yes, they run at the same time. I did one more change and now all the sanity check and unit tests are grouped. The total time decreased from 40m to 28m, any thoughts?

**Comment by brancz** [comment]
Other than that this is awesome? No :) thanks! Nice work as always!

**Pull request merged**
