### PR TITLE
Remove status field from CRDs

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
Having the status field on CRDs prevents continuous delivery tools from
converging when applying them.

### CODE REVIEW

**Comment by pgier** [comment]
These CRDs are generated by the controller-gen command (https://github.com/kubernetes-sigs/controller-tools), so the tool would need to be configured to avoid generating these fields.  I'm not sure if this is currently possible with controller-gen.

**Comment by yann-soubeyrand** [comment]
Yes I've just seen the issue you opened for creationTimestamp.

**Comment by mcristina422** [comment]
I've updated controller-tools with a potential fix https://github.com/kubernetes-sigs/controller-tools/pull/433

**Comment by yann-soubeyrand** [comment]
> I've updated controller-tools with a potential fix [kubernetes-sigs/controller-tools#433](https://github.com/kubernetes-sigs/controller-tools/pull/433)

Thanks a lot!

**Pull request closed without merging**
