### PR TITLE
StatefulSets

### PR DESCRIPTION
**Pull request by brancz**
Do you think we should include the release notes for `v0.2.0` Changelog in here so we can directly create the release once we're done with the switch to `StatefulSet`s? Because it will cause confusion mentioning the versions in the migration documentation if `v0.2.0` was not yet released.

Wdyt @fabxc @alexsomesan ?

Other than that I've tested with the e2e tests so far (with latest minikube) and will do some more manual testing before merging this.

### CODE REVIEW

**Comment by fabxc** [comment]
Great, that generally looks all good to me 👍 

I saw we switches in some places from generic `api` package to `v1` and similar things. In a lot of these cases the types where defined multiple times across different packages.
Did the duplications go away? Were we using the wrong one? (I think we just picked the initial ones because it got us to something compiling the fastest.)

**Comment by brancz** [comment]
@fabxc the changes were mainly due to type changes expected from the particular `Client`, like the `PodClient`, `ConfigMapClient`, etc. that originate from the `/kubernetes` package of `client-go`.

I will write up some release notes and then we will do the release.

**Comment by fabxc** [comment]
Great, thanks.

@alexsomesan if you are using client-go for the Tectonic operator, you'll probably use the newer version as well if you aren't already.
Seems like it cleaned up quite a few things.

**Comment by alexsomesan** [comment]
@fabxc I was using the 1.5 pinned version as well. I'll switch it now.

**Pull request merged**
