### PR TITLE
Add log format support for Prometheus

### PR DESCRIPTION
**Pull request by hypnoglow**
Prometheus 2.6.0 introduced JSON log format support. This commit makes
possible to configure log format through prometheus spec.

### CODE REVIEW

**Comment by metalmatze** [comment]
This needs a rebase against the current `master` and then another round of `make generate` from the root. Otherwise LGTM

**Comment by hypnoglow** [comment]
I have no idea why my `make generate` negates [these](https://github.com/coreos/prometheus-operator/pull/2319/commits/ce8c0941d04a26dc6c78149036467e254fafb754) changes. I've also tried `make generate-in-docker`. Can someone direct me what am I doing wrong? I've rebased on e578c3af and running generate from the root.

**Comment by metalmatze** [comment]
Try running `make clean` before the generation.

**Comment by hypnoglow** [comment]
> Try running make clean before the generation.

Thanks, it helped!

**Pull request merged**
