### PR TITLE
Build ARM images for Operator and sidecars

### PR DESCRIPTION
**Pull request by metalmatze**
This will make the Dockerfiles multi-arch. I'm currently trying to figure out how to propagate the different build flags through Makefile and some scripts.

/cc @rhuss

### CODE REVIEW

**Comment by brancz** [comment]
Nice! lgtm on green

**Comment by paulfantom** [comment]
It might be good to use https://docs.docker.com/buildx/working-with-buildx/ for this.

**Comment by metalmatze** [comment]
Oh nice @paulfantom. I didn't know about that. Let me check it out! :100:

**Comment by rhuss** [comment]
> It might be good to rewrite them to use https://docs.docker.com/buildx/working-with-buildx/.

This would be even more awesome. My typical workflow (with Docker Desktop on macOS) is:

```
# Prepare
docker buildx create --name xbuilder
docker buildx use xbuilder
docker buildx inspect --bootstrap

# Build
docker buildx build --platform linux/arm/v7,linux/amd64 --push -t myrepo/myimage .
```

Assuming that the base image is also Multiarch (coming with a Manifest), this will create also a multiarch image with the proper manifest and push it to the registry.

I'm note really fluent neither with buildx nor Manifest, so can't really say how to integrate that into the build.

**Comment by rhuss** [comment]
This is a nice article with kind of step-by-step tutorial: https://medium.com/@carlosedp/cross-building-arm64-images-on-docker-desktop-254d1e0bc1f9

**Comment by olvesh** [comment]
I was just looking for a multi arch images for my pie hobby project. But will this work on quay.io? I tried to pull `docker manifest inspect quay.io/coreos/kube-state-metrics:latest` and it fails and docker pull gives me a deprecation warning (see my comment here https://github.com/coreos/prometheus-operator/issues/2946#issuecomment-573362693 )

**Comment by rhuss** [comment]
I have not really experienced with manifest handling on quay, but what I tried is:

```
# Prepare builder container within docker
docker buildx create --name xbuilder
docker buildx use xbuilder

# compile, build and push with buildkit:
docker buildx build -f crossbuild.dockerfile --platform linux/arm/v7,linux/amd64 --progress plain --push -t rhuss/prometheus-operator .
```

with this multi-stage Dockerfile:

```dockerfile
FROM golang:1.13-alpine AS builder

WORKDIR /opt
COPY . /opt/

RUN CGO_ENABLED=0 go build -mod=vendor -ldflags="-s -X github.com/coreos/prometheus-operator/pkg/version.Version=0.34.0" -o operator cmd/operator/main.go

# Pick up from build
FROM quay.io/prometheus/busybox:latest

COPY --from=builder /opt/operator /bin/operator

# On busybox 'nobody' has uid `65534'
USER 65534

ENTRYPOINT ["/bin/operator"]
```

The build part was extracted from the Makefile (with the version being hardcoded for now).

The result can be seen at https://hub.docker.com/repository/docker/rhuss/prometheus-operator/tags?page=1 (note the "Arch/OS" column)

Maybe something like this could work in a general fashion, too ? I've seen other Travis/CircleCI setup that uses qemu for cross building in the CI and using the manifest-tool to create the manifest. Could be worth to checkout to avoid a hard depedency on Docker's buildkit.

**Comment by paulfantom** [comment]
So we have 2 ways of doing this:
1) building binary inside a container and using multi-stage builds with `buildkit` (essentially https://github.com/coreos/prometheus-operator/pull/2947#issuecomment-573419338)
2) having simple Dockerfile, like the one in this PR and building binaries outside. This is essentially what prometheus ecosystem is using.

I am a bit more keen on the latter approach as it doesn't need any qemu tricks since golang can handle cross-compilation by itself.

**Comment by rhuss** [comment]
> I am a bit more keen on the latter approach as it doesn't need any qemu tricks since golang can handle cross-compilation by itself.

I agree that this approach is better, especially as it doesn't require a hard dependency on Docker. However, the second approach only works nicely if you only have to add a self-compile binary. If you need to install some packages, you do have to run the build in the target context (qemu or buildkit). 

There are tons of example out there how folks are building multi-arch images via public CI systems like circleci or travis. I like the approach in e.g. https://github.com/jimmidyson/configmap-reload/ which has a good blueprint for go crosscompiling and also creating the proper manifest needed for a multi-arch image (e.g. https://github.com/jimmidyson/configmap-reload/blob/7ff0bc9a293fd39b022910be59dbc9292fc2ceb7/.circleci/config.yml#L56-L133)

The question really is, how this works together with quay.io. I have no idea if there is any and how good the multi-arch support with manifest is at quay. My first experiments were not so positive (so I actually push to Docker hub). I understand, that Docker Hub is not an option, so would love to learn how to work with manifest on Quay.

**Comment by paulfantom** [comment]
> If you need to install some packages

prometheus-operator doesn't need anything apart from its binary and I wrote it with this repo in mind ;)

> The question really is, how this works together with quay.io.

We need to have multiple repos for storing images for different architectures and one meta repo for storing virtual image (manifest). This is also how prometheus is distributed.

> I like the approach in e.g. jimmidyson/configmap-reload which has a good blueprint for go crosscompiling

I also like it, but I might be a bit biased as I wrote it (https://github.com/jimmidyson/configmap-reload/pull/35) :smile:

**Comment by rhuss** [comment]
> I also like it, but I might be a bit biased as I wrote it ([jimmidyson/configmap-reload#35](https://github.com/jimmidyson/configmap-reload/pull/35)) 😄

LOL, the world is so small :)

**Comment by metalmatze** [comment]
I agree that using plain Dockerfiles and tags would be best. I'm not even sure how to enable these things on Travis.

**Comment by Sergio123** [comment]
hi guys, any updates on this?

**Comment by paulfantom** [comment]
Added in #3035
Automation for building cross-arch images is in #3177

**Comment by amintek** [comment]
hi guys, is there any change to get ppc64le images for Operator and sidecars

**Comment by simonpasquier** [comment]
@amintek it should be fairly easy to add if you want to give it a try

https://github.com/prometheus-operator/prometheus-operator/blob/7925986b5e53ea40413d74ae221603e26f2b3d50/scripts/push-docker-image.sh#L19

**Comment by amintek** [comment]
@simonpasquier : how can i do so to get ppc64le docker images ?

**Pull request closed without merging**
