### PR TITLE
Update Alert Manager rules for NodeDiskRunningFull with summary

### PR DESCRIPTION
**Pull request by alexanderdavidsen**
Update rules with summary for better notifications.

### CODE REVIEW

**Comment by brancz** [comment]
lgtm on green

**Comment by alexanderdavidsen** [comment]
Forgot to update the kube-prometheus version. Fixed now.

**Comment by brancz** [comment]
`contrib/` changes lgtm, all good on the helm charts @gianrubio ?

**Comment by gianrubio** [comment]
All good in helm charts!

**Pull request merged**
