### PR TITLE
prometheus-config-reloader: support for watching rules directory

### PR DESCRIPTION
**Pull request by leoluk**
Add --rules-dirs to expose the directory watching feature of the reloader library.

### CODE REVIEW

**Comment by pgier** [comment]
Thanks for the contribution, but this is currently failing CI.  I'm not sure why it's failing, but I'm guessing this is because when no `rulesDir` is set, the call to `reloader.New()` is passing a slice with a single empty string value instead of an empty slice.  You might need to just add a check for empty string and pass an empty slice in that case.

**Comment by leoluk** [comment]
Yup, that's what happened. Hooray for tests!

**Comment by leoluk** [comment]
Checks are now passing, there was a much easier way to do this using Kingpin's repeatable arguments.

**Comment by brancz** [comment]
I feel like I’m missing context. Is there an issue or something why we needed this?

**Comment by leoluk** [comment]
Without this flag, the reloader is only able to catch modifications to prometheus.yml, not individual rules files. I'm using the reloader as a standalone container - how does the operator solve this?

**Comment by brancz** [comment]
We use the configmap reloader instead. But we did say that one day we wanted to merge them back together.

**Comment by brancz** [comment]
RE https://github.com/coreos/prometheus-operator/issues/1580

**Pull request merged**
