### PR TITLE
parameterize the global scrape_interval in prometheus config

### PR DESCRIPTION
**Pull request by nrobert13**
allow to customize the scrape_interval in the global section of the prometheus

### CODE REVIEW

**Comment by brancz** [comment]
Neat! Thanks for the contribution!

Could you run `make generate`, to re-generate the API docs from the code? :slightly_smiling_face:

**Comment by nrobert13** [comment]
doku updated.

**Comment by brancz** [comment]
@coreosbot test this please

**Comment by brancz** [comment]
@coreosbot test this please

**Comment by brancz** [comment]
Having some trouble with CI so I ran tests myself, and it all looks good, thanks! :+1:

**Pull request merged**
