### PR TITLE
helm/exporter-kubelets: Add option to use the http-metrics port inste…

### LINKED ISSUE #902: Query kubelet via proxy / metricRelabelings issue
Default helm deployment doesn't work out of the box as kublet querying doesn't work
There is an issue to fix the cadvisor part #633 
Another issue is that on some cluster token auth doesn't work on the kubelet https endpoint (at least on GKE (https://github.com/kubernetes/kubernetes/issues/44330 https://github.com/prometheus/prometheus/issues/2606#issuecomment-294869099 https://github.com/prometheus/prometheus/pull/2641 https://kubernetes.io/docs/admin/kubelet-authentication-authorization/#kubelet-authentication) and kubespay)

The proper fix, which is in prometheus repo, is to query trough the API server using relabeling black magic
https://github.com/prometheus/prometheus/blob/fae3bd17b950f4574a0827d975e4e7df80d5abfb/documentation/examples/prometheus-kubernetes.yml#L59

**What did you do?**
Try to use metricRelabelings
```
diff --git a/helm/exporter-kubelets/templates/servicemonitor.yaml b/helm/exporter-kubelets/templates/servicemonitor.yaml
index 69718e4..8c6e226 100644
--- a/helm/exporter-kubelets/templates/servicemonitor.yaml
+++ b/helm/exporter-kubelets/templates/servicemonitor.yaml
@@ -26,6 +26,15 @@ spec:
       # for the kubelet on API server nodes fail.
       insecureSkipVerify: true
     bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
+    metricRelabelings:
+    - action: labelmap
+      regex: __meta_kubernetes_node_label_(.+)
+    - targetLabel: __address__
+      replacement: kubernetes.default.svc:443
+    - sourceLabels: [__meta_kubernetes_node_name]
+      regex: (.+)
+      targetLabel: __metrics_path__
+      replacement: /api/v1/nodes/${1}/proxy/metrics
   - port: cadvisor
     interval: 30s
     honorLabels: true
```

**What did you expect to see?**
see this conf "mixed" into prometheus conf (/conf)

**What did you see instead? Under which circumstances?**
nothing is happening, `metricRelabelings` section is ignored
(no error in the operator logs)

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0+coreos.0", GitCommit:"1b69a2a6c01194421b0aa17747a8c1a81738a8dd", GitTreeState:"clean", BuildDate:"2017-12-19T02:52:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0+coreos.0", GitCommit:"1b69a2a6c01194421b0aa17747a8c1a81738a8dd", GitTreeState:"clean", BuildDate:"2017-12-19T02:52:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
Installed a default cluster on Centos 7.4 node using kubespay

* Prometheus Operator version:
latest version (1fb131970e93e35f37db3dbc2fbee66e35ca696f) deployed from git using helm

### PR DESCRIPTION
**Pull request by binoculars**
…ad of the https-metrics port

Needed for GKE due to the issue with kubelet serviceaccount token auth. Port 10255 (http-metrics) is open on GKE.

Fixes #902

Related: #485, #773

### CODE REVIEW

**Comment by binoculars** [comment]
@gianrubio requested changes made

**Comment by kongslund** [comment]
I have an additional request. Scrape cAdvisor metrics from the `https-metrics` port on `/metrics/cadvisor` instead of through the `cadvisor` port. The latter is bound to disappear and it is more secure to use `https-metrics`.

This is equivalent to what @brancz did for kube-prometheus in #908. See commit https://github.com/coreos/prometheus-operator/pull/908/commits/8928e071da28c9a93ebc0d0590f9bf8ebce2663f

Note that doing so requires additional RBAC permission for `nodes/metrics`. Luckily this was already added to `helm/prometheus/templates/clusterrole.yaml` as part of #901

**Comment by kongslund** [comment]
I realize that my request may overload the scope for this PR. Please disregard it if you find that this is the case. I will add it as a separate PR once this one is merged.

**Comment by gianrubio** [comment]
Thanks @binoculars

**Comment by gianrubio** [comment]
@kongslund could you address this changes in a new PR?

**Comment by kongslund** [comment]
@gianrubio I've created PR #910

**Comment by binoculars** [comment]
Thanks for merging! One quick thing--I did `helm repo update` to get the new charts and exporter-kubelets was updated, but kube-prometheus didn't get the change. Would it be possible to run `helm dep up` to pull the changes in?

**Pull request merged**
