### PR TITLE
helm: allow to modify prometheus log level

### PR DESCRIPTION
**Pull request by luisyonaldo**
Allow to modify prometheus log level when using helm charts

### CODE REVIEW

**Comment by gianrubio** [comment]
Sorry, there's flaky tests, could you rerun the CI? When it's green I'll merge it

**Comment by luisyonaldo** [comment]
sure, right now I'm testing locally. Even when `Prometheus` CRD have `logLevel` defined, prometheus container does't have `--logLevel` argument

**Comment by luisyonaldo** [comment]
my bad, chart have latest version of operator, somehow `helm upgrade` didn't bump version of operator

**Comment by gianrubio** [comment]
Thanks @luisyonaldo

**Pull request merged**
