### PR TITLE
helm: Update prometheus to v2.3.2

### PR DESCRIPTION
**Pull request by mrueg**
This one might depend on https://github.com/coreos/prometheus-operator/pull/1670 I'll rebase it when https://github.com/coreos/prometheus-operator/pull/1670 got merged.

### CODE REVIEW

**Comment by brancz** [comment]
There's no dependency on #1670 , but it's also already merged :slightly_smiling_face: .

**Comment by mrueg** [comment]
Yep, had some other issue. CI is green now. :) 
@gianrubio

**Comment by mrueg** [comment]
@gianrubio done, added a note in the comment

**Comment by michaelgeorgeattard** [comment]
Any updates on this?

**Comment by gianrubio** [comment]
Sorry for the inconvenience, but the prometheus-operator and kube-prometheus helm charts are currently being migrated to the upstream stable helm charts. Because of this we are currently not accepting any pull requests. We apologize for the inconvenience, but this is necessary for the migration to actually happen. We announced this here: https://github.com/coreos/prometheus-operator/tree/master/helm#warning

You can view the progress and help [here](https://github.com/coreos/prometheus-operator/issues/592) and [here](https://github.com/helm/charts/pull/6765).

Thank you for your understanding! :slightly_smiling_face:

**Pull request closed without merging**
