### PR TITLE
Adding master toleration to node-exporter daemonset in kube-prometheus

### LINKED ISSUE #1241: kube-prometheus node-exporter does not have standard master tolerations
**What did you do?**
Installed prometheus operator using the kube-prometheus manifests

**What did you expect to see?**
Node-exporter running on all nodes (including masters)

**What did you see instead? Under which circumstances?**
Node exporter does not have toleration for node-role.kubernetes.io/master

**Environment**
OSX

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
kops

* Manifests:

```
prometheus-operator/contrib/kube-prometheus/manifests/node-exporter/node-exporter-daemonset.yaml```

I have forked this repo and will open a PR, but wanted an issue to go with it in case I missed something.

### PR DESCRIPTION
**Pull request by sudermanjr**
Fixes #1241 .  Adding standard master toleration for node-exporter.

### CODE REVIEW

**Comment by brancz** [comment]
The daemonset is generated from the jsonnet code in `contrib/kube-prometheus/jsonnet/node-exporter`. Tolerations would be similarly added as [volumes](https://github.com/coreos/prometheus-operator/blob/5bd9dbf774a49569240b67c1a3298d1bb9dad2d5/contrib/kube-prometheus/jsonnet/node-exporter/node-exporter-daemonset.libsonnet#L54).

You need to use the `local toleration = daemonset.mixin.spec.template.spec.tolerationsType;`, so create the toleration you proposed, like so:

```
local masterToleration = toleration.new() +
    toleration.withEffect("NoSchedule") +
    toleration.withKey("node-role.kubernetes.io/master");
```

Then the toleration can then be added by using the toleration mixin similar to the [volumes](https://github.com/coreos/prometheus-operator/blob/5bd9dbf774a49569240b67c1a3298d1bb9dad2d5/contrib/kube-prometheus/jsonnet/node-exporter/node-exporter-daemonset.libsonnet#L54), just using:

```
          daemonset.mixin.spec.template.spec.withTolerations([masterToleration]) +
```

**Comment by sudermanjr** [comment]
@brancz Thanks for all the info.  I will work on that.

**Comment by bamb00** [comment]
Has anyone tested the toleration as provided in manifest? I deploy node-exporter with the tolerations below and it seems not to be working as the node-exporter did not get create in the master nodes but the node-exporter only get created in the client-node.  Hope that I use it correctly.  Any ideas?

         tolerations:
            - key: node-role.kubernetes.io/master
               effect: NoSchedule

**Comment by brancz** [comment]
we test them in our e2e tests so generally this seems to work

**Pull request closed without merging**
