### PR TITLE
Move to v1 from v1alpha1

### PR DESCRIPTION
**Pull request by brancz**
The main change that we had to do here is that we needed to not do one TPR after another but all TPRs step by step, but each step for all TPRs, then we could successfully register and reach the api group.

@fabxc

### CODE REVIEW

**Comment by brancz** [comment]
@mxinden out of my own necessity I added the code for #503 as my latest commit.

**Comment by brancz** [comment]
@coreosbot test this please

**Comment by brancz** [comment]
@coreosbot test this please

**Comment by fabxc** [comment]
👍

**Comment by brancz** [comment]
@coreosbot test this please

**Pull request merged**
