### PR TITLE
Update configmap-reload image from upstream

### PR DESCRIPTION
**Pull request by qw1mb0**
fix: #2498

### CODE REVIEW

**Comment by brancz** [comment]
while I understand this, I'd prefer if we could move all of these into the prometheus operator repo, as it's very hard to reason about what is happening when this is an external container

**Comment by qw1mb0** [comment]
How can i do this? I can make a separate directory with Dockerfile:
```
FROM jimmidyson/configmap-reload:v0.2.2
```

Then you will need to configure auto build? Or how to do it right?

**Comment by brancz** [comment]
I'd be ok with that. We already have two dockerfiles, I'd be ok with adding this one as well. Or we could consolidate and merge the functionality from configmap-reload into the sidecar whose code is already in this repo.

**Comment by mrueg** [comment]
@qw1mb0 are you still planning to work on this issue?

**Comment by pgier** [comment]
Closing this because a similar update was merged in #2952

**Comment by xUnholy** [comment]
Was this forgotten to be updated in the helm charts? https://github.com/helm/charts/blob/bd697f1f5b248fda127ffa0b3dfaa2fdac0f55fc/stable/prometheus-operator/values.yaml#L1268

**Pull request closed without merging**
