### PR TITLE
contrib: fix typo in contrib prometheus rules

### PR DESCRIPTION
**Pull request by kkc**
Change `Promehteus` to `Prometheus`

### CODE REVIEW

**Comment by kkc** [comment]
It took me a while to understand why the testing failed. 
When it tests `contrib/kube-prometheus/`, it will execute `jb install github.com/coreos/prometheus-operator/contrib/kube-prometheus/jsonnet/kube-prometheus` which downloads the old file including `Promehteus`. 
It turns out the comparison failed between the new file and old file, and I don't know how to fix this kind of error. 

@metalmatze can you give me some guidance on how to modify it to pass the test? Thanks a lot

**Comment by gianrubio** [comment]
Sorry for the inconvenience, but the prometheus-operator and kube-prometheus helm charts are currently being migrated to the upstream stable helm charts. Because of this we are currently not accepting any pull requests. We apologize for the inconvenience, but this is necessary for the migration to actually happen. We announced this here: https://github.com/coreos/prometheus-operator/tree/master/helm#warning

You can view the progress and help [here](https://github.com/coreos/prometheus-operator/issues/592) and [here](https://github.com/helm/charts/pull/6765).

Thank you for your understanding! :slightly_smiling_face:

**Comment by gianrubio** [comment]
Oh sorry, I closed the issue because I thought was only helm related. Feel free to remove the helm changes and reopen it.

**Comment by squat** [comment]
Looks like a flake. Restarting tests

**Comment by kkc** [comment]
@squat what should I supposed to do? just close PR and reopen it to restart tests?

**Comment by metalmatze** [comment]
Travis allows for restarting the tests with a click of a button and then report back the results to github. No need to do anything here. 😊

**Comment by brancz** [comment]
lgtm thanks!

**Pull request merged**
