### PR TITLE
Docs: Update Getting-Started examples

### PR DESCRIPTION
**Pull request by gjtempleton**
Updates getting-started example yaml scripts to match
their declared purpose - creates 2 new snippets to
achieve this.

Signed-off-by: GuyTempleton <guy.templeton@skyscanner.net>

### CODE REVIEW

**Comment by gjtempleton** [comment]
I did briefly consider doing this by adding some generation to modify the one existing file to dynamically create the 2 new files during the running of `make generate`, but this seemed likely to be a net loss on the ease of understanding how the yaml was appearing in the .md so just created the 2 small new files.

**Comment by s-urbaniak** [comment]
This LGTM, thanks a lot :+1:

**Comment by s-urbaniak** [comment]
cc @paulfantom @simonpasquier @pgier for verification

**Comment by s-urbaniak** [comment]
not sure why this is still showing "pending check", the build is green, hence merging.

**Pull request merged**
