### PR TITLE
scripts/tooling: use latest and greatest tooling binaries

### PR DESCRIPTION
**Pull request by paulfantom**
Updating dependencies:
- jsonnet 0.15.0
- golanglint 1.23.6
- promtool 2.16.0
- jsonnet-bundler ~0.3.0~ 0.3.1 (when it gets released :slightly_smiling_face: )

WIP until jsonnet-bundler 0.3.0 is released
/cc @metalmatze @brancz

### CODE REVIEW

**Comment by metalmatze** [comment]
jb v0.3.1 was released, @paulfantom :blush:

**Comment by paulfantom** [comment]
All done.

**Comment by metalmatze** [comment]
merge on green :)

**Comment by simonpasquier** [comment]
LGTM

**Pull request merged**
