### PR TITLE
Enable logFormat in helm / Forward option from operator to p-c-r 

### PR DESCRIPTION
**Pull request by mrueg**
Follow-up PR of https://github.com/coreos/prometheus-operator/pull/1475

### CODE REVIEW

**Comment by brancz** [comment]
lgtm

**Comment by mrueg** [comment]
anything missing here to get this merged, or does it require @gianrubio to take a look at the helm part?

**Comment by brancz** [comment]
Yeah sorry I was waiting for @giantubio to have a look.

**Comment by gianrubio** [comment]
sorry for the long delay reviewing this PR
/lgtm on green

**Pull request merged**
