### PR TITLE
helm/kube-prometheus: Use valid defaults for service nodePort values.

### LINKED ISSUE #496: helm/kube-prometheus: Values for service nodePorts in values.yaml are outside the range of valid ports.
The `nodePort` values for the **Alertmanager** and **Prometheus** services in [values.yaml](https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/values.yaml) are outside of the range of valid ports, which is `30000-32767` as described in the [docs](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport).

The default values should probably be:
* `alertmanager.service.nodePort=30903`
* `prometheus.service.nodePort=30900`

These values match what is in the `contrib` files [alertmanager](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/alertmanager/alertmanager-service.yaml) and [prometheus](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service.yaml).

**What did you do?**

Tried to install the [kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/helm/kube-prometheus) helm chart.

**What did you expect to see?**

A successful helm release.

**What did you see instead? Under which circumstances?**

1. Set up demo namespace and deploy **Prometheus Operator** via helm.

```sh
$ kubectl create namespace foo
namespace "foo" created


$ helm install opsgoodness/prometheus-operator --namespace foo --set rbacEnable=false
NAME:   lame-dragonfly
LAST DEPLOYED: Fri Jul 21 14:41:38 2017
NAMESPACE: foo
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME                                DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
lame-dragonfly-prometheus-operator  1        1        1           1          1s


NOTES:
The Prometheus Operator has been installed. Check its status by running:
  kubectl --namespace foo get pods -l "app=prometheus-operator,release=lame-dragonfly"

Visit https://github.com/coreos/prometheus-operator for instructions on how
to create & configure Alertmanager and Prometheus instances using the Operator.
```

2. Try to install `kube-prometheus` with Alertmanager service of type `NodePort`

```sh
$ helm install opsgoodness/kube-prometheus --namespace foo --set alertmanager.service.type=NodePort
Error: release cold-koala failed: Service "cold-koala-alertmanager" is invalid: spec.ports[0].nodePort: Invalid value: 39093: provided port is not in the valid range. The range of valid ports is 30000-32767
```

3. Set a valid port for the Alertmanager service and then try the same with Prometheus.

```sh
$ helm install opsgoodness/kube-prometheus --namespace foo --set alertmanager.service.type=NodePort --set alertmanager.service.nodePort=30903 --set prometheus.service.type=NodePort
Error: release bumptious-lambkin failed: Service "bumptious-lambkin-prometheus" is invalid: spec.ports[0].nodePort: Invalid value: 39090: provided port is not in the valid range. The range of valid ports is 30000-32767
```

4. Set a valid port for Prometheus too and the release is successful.

```sh
$ helm install opsgoodness/kube-prometheus --namespace foo --set alertmanager.service.type=NodePort --set alertmanager.service.nodePort=30903 --set prometheus.service.type=NodePort --set prometheus.service.nodePort=30900
NAME:   whimsical-penguin
LAST DEPLOYED: Fri Jul 21 14:45:12 2017
NAMESPACE: foo
STATUS: DEPLOYED

RESOURCES:
==> v1alpha1/Prometheus
NAME               KIND
whimsical-penguin  Prometheus.v1alpha1.monitoring.coreos.com

==> v1alpha1/Alertmanager
whimsical-penguin  Alertmanager.v1alpha1.monitoring.coreos.com

==> v1/Secret
NAME                            TYPE    DATA  AGE
alertmanager-whimsical-penguin  Opaque  1     2s

==> v1/ConfigMap
NAME                                                DATA  AGE
whimsical-penguin-exporter-kube-controller-manager  1     2s
whimsical-penguin-exporter-node                     1     2s
whimsical-penguin-exporter-kube-scheduler           1     2s
whimsical-penguin-exporter-kubelets                 1     2s
whimsical-penguin-exporter-kube-etcd                1     2s
whimsical-penguin-exporter-kube-state               1     2s
whimsical-penguin-exporter-kube-api                 1     2s
whimsical-penguin-exporter-kubernetes               1     2s

==> v1/Service
NAME                                                CLUSTER-IP     EXTERNAL-IP  PORT(S)              AGE
whimsical-penguin-exporter-kube-dns                 None           <none>       10054/TCP,10055/TCP  2s
whimsical-penguin-prometheus                        100.71.218.82  <nodes>      9090:30900/TCP       2s
whimsical-penguin-exporter-node                     100.70.220.55  <none>       9100/TCP             2s
whimsical-penguin-alertmanager                      100.69.246.66  <nodes>      9093:30903/TCP       2s
whimsical-penguin-exporter-kube-scheduler           None           <none>       10251/TCP            2s
whimsical-penguin-exporter-kube-state               100.64.4.53    <none>       80/TCP               2s
whimsical-penguin-exporter-kube-controller-manager  None           <none>       10252/TCP            2s
whimsical-penguin-exporter-kube-api                 None           <none>       443/TCP              2s
whimsical-penguin-exporter-kube-etcd                None           <none>       4001/TCP             2s

==> v1beta1/DaemonSet
NAME                             DESIRED  CURRENT  READY  UP-TO-DATE  AVAILABLE  NODE-SELECTOR  AGE
whimsical-penguin-exporter-node  3        3        3      3           3          <none>         2s

==> v1beta1/Deployment
NAME                 DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
exporter-kube-state  1        1        1           0          2s

==> v1alpha1/ServiceMonitor
NAME                                                KIND
whimsical-penguin-exporter-kubelets                 ServiceMonitor.v1alpha1.monitoring.coreos.com
whimsical-penguin-exporter-kube-controller-manager  ServiceMonitor.v1alpha1.monitoring.coreos.com
whimsical-penguin-exporter-kube-api                 ServiceMonitor.v1alpha1.monitoring.coreos.com
whimsical-penguin-exporter-kubernetes               ServiceMonitor.v1alpha1.monitoring.coreos.com
whimsical-penguin-exporter-node                     ServiceMonitor.v1alpha1.monitoring.coreos.com
whimsical-penguin-exporter-kube-state               ServiceMonitor.v1alpha1.monitoring.coreos.com
whimsical-penguin-exporter-kube-etcd                ServiceMonitor.v1alpha1.monitoring.coreos.com
whimsical-penguin-exporter-kube-dns                 ServiceMonitor.v1alpha1.monitoring.coreos.com
whimsical-penguin-exporter-kube-scheduler   
```

**Environment**

* Kubernetes version information:

```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T05:21:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

  kops

### PR DESCRIPTION
**Pull request by niclic**
This sets valid default values for service `nodePort`, avoiding errors
when using service of type NodePort.

Fixes #496

### CODE REVIEW

**Comment by niclic** [comment]
Same error in the excellent Grafana chart [here](https://github.com/coreos/prometheus-operator/blob/master/helm/grafana/values.yaml#L35)

The port is outside of the valid range. It's also the same value as the port for `alertmanager.service.nodePort`. 

I know you can _change_ these values, but I think it's important that the _defaults_ work as expected.

**Comment by brancz** [comment]
@weiwei04 ^ can you have a look at this for the grafana chart?

**Comment by brancz** [comment]
I agree with you though @niclic, I think this should be good to go, however, as always, just giving @mgoodness the last call.

**Comment by weiwei04** [comment]
@brancz @niclic yes, the grafana chart also have a invalid default nodePort: 39093, @niclic could please correct the grafana chart too, thanks.

**Comment by niclic** [comment]
I can update the grafana chart, no problem. However, I also just noticed that the ports in [helm/alertmanager](https://github.com/coreos/prometheus-operator/blob/master/helm/alertmanager/values.yaml) and [helm/prometheus](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/values.yaml) also need changing.

@brancz I would look for thumbs up that I should include changes for these charts too before making any further changes. I think it makes sense for all charts to be updated in this PR with consistent and correct `nodePort` values.

**Comment by niclic** [comment]
Suggested `nodePort` values:

* `prometheus`: `30900`
* `grafana`: `30902`
* `alertmanager`: `30903`

These are the values used in [contrib/kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests).

**Comment by brancz** [comment]
All of the above sounds good to me.

**Comment by niclic** [comment]
Okay. Changes made. @brancz @weiwei04

**Comment by weiwei04** [comment]
lgtm, may be need to bump the chart version in Chart.yaml.

**Comment by brancz** [comment]
As far as I understand we do need to, otherwise we/@mgoodness can't release the new version of the chart.

**Comment by niclic** [comment]
Ah, I see. I'm new to helm, so did not know that. Makes sense. 

There are four helm charts that have been modified here. This implies that all four need a (patch) version bump.

If so, then I should probably also modify https://github.com/coreos/prometheus-operator/pull/499.

**Comment by brancz** [comment]
Most likely yes on both of those. We're currently relying on the community to maintain the helm charts, as we're not actively using them ourselves, but we understand the community likes it so we have no objection to having them. What I'm saying is, all help appreciated! :slightly_smiling_face:

**Comment by brancz** [comment]
lgtm thanks!

**Pull request merged**
