### PR TITLE
Fix AlertmanagerMembersInconsistent rule

### PR DESCRIPTION
**Pull request by BcTpe4HbIu**
Fix for #2142

### CODE REVIEW

**Comment by brancz** [comment]
In a separate commit, could you run `jb update` in the `contrib/kube-prometheus/` directory, and then run `make generate-in-docker` in the root of the repo? Thanks! :slightly_smiling_face:

**Comment by metalmatze** [comment]
We should also make sure to update the alert unit test accordingly.
The rules can be generated from jsonnet to YAML with 
```bash
cd contrib/kube-prometheus
jsonnet -J vendor -e '(import "jsonnet/kube-prometheus/kube-prometheus.libsonnet").prometheusAlerts' | gojsontoyaml > jsonnet/kube-prometheus/alerts/rules.yaml
cd jsonnet/kube-prometheus/alerts
promtool test rules tests.yaml # to run the tests
```

Sadly there are no docs yet on this, as it is an temporary solution.
The promtool can be found [here](https://prometheus.io/download/) as part of the Prometheus release.

**Comment by BcTpe4HbIu** [comment]
@brancz Done as you said - now tests are complaining about ref not in tree. contrib/kube-prometheus/jsonnetfile.lock.json shoud not be commited?

**Comment by metalmatze** [comment]
Yep. You need to update the `jsonnetfile.lock.json` with a valid commit sha. As you have rebased the previous commit referenced doesn't exist anymore.
Run `git log`, pick the last commit sha and replace the one with it: 
https://github.com/coreos/prometheus-operator/pull/2143/files#diff-88fe225f23f7d800f3c1d43af3ae198aR11

**Comment by BcTpe4HbIu** [comment]
@brancz @metalmatze All done

**Comment by brancz** [comment]
lgtm :+1: thanks!

**Comment by metalmatze** [comment]
Awesome. Thank you!

**Pull request merged**
