### PR TITLE
Update thanos to 0.4.0

### PR DESCRIPTION
**Pull request by vsliouniaev**
The migration to go-mod removed #2504, which means that #2501 was still present in [v0.30.0](https://github.com/coreos/prometheus-operator/releases/tag/v0.30.0)

### CODE REVIEW

**Comment by squat** [comment]
very nice catch :) thanks

**Comment by brancz** [comment]
Not sure the CI errors were flakes or not. Restarted them but we should keep an eye out for it.

**Comment by vsliouniaev** [comment]
Don't have a good idea on where to start trying to fix the build. It reads like a permission issue with bzr inside the custom docker image used to build

**Comment by paulfantom** [comment]
We are running commands as an unprivileged user inside a container and `/usr/bin/bzr` wants that user to exist, but it doesn't. This is essentially this python bug: https://bugs.python.org/issue31469 which can be solved with a following patch:

```patch
diff --git a/Makefile b/Makefile
index 84b66004..e8c7d6b8 100644
--- a/Makefile
+++ b/Makefile
@@ -34,6 +34,8 @@ CONTAINER_CMD:=docker run --rm \
                -v "$(PWD):/go/src/$(GO_PKG):Z" \
                -w "/go/src/$(GO_PKG)" \
                -e GO111MODULE=on \
+               -e USER=deadbeef \
                quay.io/coreos/jsonnet-ci
 
 .PHONY: all
```

It is a bit funny that you need python to download a go library, but that is a case for those two projects as they are using bazaar as their VCS (probably because they are hosted on launchpad.net):
- labix.org/v2/mgo
- launchpad.net/gocheck

**Comment by vsliouniaev** [comment]
Thanks a lot @paulfantom

**Comment by brancz** [comment]
Thanks! lgtm :+1:

**Pull request merged**
