### PR TITLE
Add ability to define service ports for Prometheus & Alertmanager

### PR DESCRIPTION
**Pull request by lostick**
Only `NodePort` can be changed presently on Prometheus and AlertManager.

I've updated these charts to allow multiple port definitions to be defined.
This is very useful in cases such as federation over https.

NB: Charts minor versions have been increased to indicate that this is a not a bugfix.
NB2: Prometheus bumped to `2.3.2` as well. This fix seems to fix the TSDB memory issues we were encountering at the federation level.

### CODE REVIEW

**Comment by brancz** [comment]
Sorry for the inconvenience, but the prometheus-operator and kube-prometheus helm charts are currently being migrated to the upstream stable helm charts. Because of this we are currently not accepting any pull requests. We apologize for the inconvenience, but this is necessary for the migration to actually happen. We announced this here: https://github.com/coreos/prometheus-operator/tree/master/helm#warning

You can view the progress and help [here](https://github.com/coreos/prometheus-operator/issues/592) and [here](https://github.com/helm/charts/pull/6765).

Thank you for your understanding! :slightly_smiling_face:

**Comment by lostick** [comment]
@brancz fair enough :),

**Comment by vsliouniaev** [comment]
@lostick you're welcome to test stable/prometheus-operator now :-)

**Comment by metalmatze** [comment]
The Helm chart has moved to https://github.com/helm/charts/tree/master/stable/prometheus-operator please open a PR there.
Thank you for your contribution!

**Pull request closed without merging**
