### PR TITLE
Adding Volumes to PrometheusSpec

### PR DESCRIPTION
**Pull request by rchapple**
pkg: PrometheusSpec api updated, StatefulSet generation updated to match

Added ability to express additional Volumes on the PrometheusSpec object, and to have those Volumes propagated out to the generated StatefulSet config.

Fixes: #2708

cc: @brancz

### CODE REVIEW

**Comment by LiliC** [comment]
@rchapple restarted that one, it timed out, the other job that failed earlier passed now.

**Comment by brancz** [comment]
lgtm :+1: thank you! :)

**Comment by benjaminhuo** [comment]
Just wondering the additional volumes are used for what purpose?

Thanks
Ben

**Comment by brancz** [comment]
Only for mounting secret information such as using a vault csi provider.

**Comment by benjaminhuo** [comment]
Thanks for the quick response :)

**Pull request merged**
