### PR TITLE
Update To Grafana 5.0.3

### PR DESCRIPTION
**Pull request by michaelpietzsch**

### CODE REVIEW

**Comment by brancz** [comment]
could you update all the places where it is used as well?

**Comment by michaelpietzsch** [comment]
Is the upload to Quay automated? ... because sanity checks will fail if the image is not uploaded

**Comment by brancz** [comment]
Currently it is not automated, we're hoping to get our needs into the upstream image eventually. I will push it and re-build, that way it will work :slightly_smiling_face:

**Comment by brancz** [comment]
Grafana has since been upgraded to v5.1.x

**Pull request closed without merging**
