### PR TITLE
Change roleBindingSpecificNamespaces to use $._config.namespace

### PR DESCRIPTION
**Pull request by vasrem**
There is an issue which leads to the creation of RoleBindings which are correlated with ServiceAccounts which don't exist. This change will allow each RoleBinding to be attached to the ServiceAccount created on [this](https://github.com/coreos/prometheus-operator/blob/bb1966b2a1dc737d67f8f72983c747f0b5732947/contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet#L29-L33) section.

The issue was created after merging #1708.

### CODE REVIEW

**Comment by brancz** [comment]
You're absolutely correct. Could you just run `make generate-in-docker` from the root of the repo and commit the changes? Thanks!

**Comment by vasrem** [comment]
I have already run this but I get nothing new to commit.

**Comment by brancz** [comment]
I pushed another commit on top of your branch that re-generates and updates the jsonnet dependencies. This should be good now, let's just see CI pass :slightly_smiling_face: .

**Comment by brancz** [comment]
Oh. It actually looks like we broke jsonnet-bundler today. It's time to sleep over here. I'll try to fix everything in the morning.

**Comment by brancz** [comment]
Thanks a lot for taking care of this @vasrem! Highly appreciated!

**Pull request merged**
