### PR TITLE
Remove apiextensions.k8s.io/v1beta1 CRDs

### PR DESCRIPTION
**Pull request by dgrisonnet**
Follow-up PR from this [discussion](https://github.com/coreos/prometheus-operator/issues/3178#issuecomment-621128023).

cc @pgier @brancz @lilic

### CODE REVIEW

**Comment by s-urbaniak** [comment]
lgtm

**Comment by benjaminhuo** [comment]
@dgrisonnet This mean prometheus operator v0.39 and above only supports K8s 1.16 +?
then what this PR used for? https://github.com/coreos/prometheus-operator/pull/3175 , it generates both v1 and v1beta1 CRDs

Thanks
Ben

**Comment by dgrisonnet** [comment]
Yes, prometheus operator v0.39+ will only support k8s 1.16+.

The original plan, when we wanted to update CRDs to v1 was to preserve compatibility with the 4 latest versions of Kubernetes. Meaning that we needed to add a mechanism to generate both v1 and v1beta1 CRDs.

Unfortunately, we later found out that keeping v1beta1 was dragging us down when updating controller-tools, which was the main purpose of updating CRDs #3137. So in the end, we preferred getting rid of v1beta1 in favor of updating controller-tools and thus have further validations on the CRDs.

**Comment by benjaminhuo** [comment]
Got it , thanks very much for these background info.

Ben

**Pull request merged**
