### PR TITLE
documentation: clarify _RelabelConfig_ usage

### PR DESCRIPTION
**Pull request by opusmagnum**
The _RelabelConfig_ is confusing and connotes, that it is about `<relabel_config>`-section of the configuration, but in reality it is about `<metric_relabel_configs>`-section.

#1014

### CODE REVIEW

**Comment by brancz** [comment]
Sorry for the confusion! And thanks for taking the time to contribute!

The relabelconfig struct is actually relevant for any relabeling configuration, I would prefer, if we add a comment like this into the actual `metricsRelabelConfig` field, here: https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1/types.go#L312-L313

Also note that the API docs are generated, so we need to change it in the actual type definition as seen above, then you can just regenerate the docs by running `make generate` in the root of the repo. Thanks! :slightly_smiling_face:

**Comment by opusmagnum** [comment]
Thank you @brancz to look into it,
understood with the API-documentation source.

Your comment in the code is terse and clear for everybody, who is deep in Prometheus Configuration/relabeling. But believe me, newbies will be glad to have a link to the appropriate detailed documentation section of Prometheus configuration as well. It is about quicker and easier adoption of Prometheus-operator.

**Comment by brancz** [comment]
Understood and agreed. In that case, could you just adapt the text here: https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1/types.go#L221

And then run the `make generate` target? Thanks!

**Comment by opusmagnum** [comment]
I have added code comment in `types.go` and run `make generate` afterwards. Travis CI build is failing on this feature branch? The reason is unclear to me (Golang beginner ;). 
Thanks in advance.

**Comment by brancz** [comment]
To be honest I don't know where this happens, but I get the same result as CI when I just run `./scripts/check-make-generate.sh`. Could you just run that and satisfy CI? :slightly_smiling_face:

**Comment by opusmagnum** [comment]
There was a space at the end of the line. Travis CI run `./scripts/check-make-generate.sh` script and found it out, because it makes `git diff --exit-code` at the end. But this space in question was not visible with "normal" diff. I found it out with -- `git diff --color --ws-error-highlight=new,old`. 
Fixed and commited.

PS: Travis CI will always fail if `go fmt` changes something relative to already commited code. I see few other pull requests failed Travis CI, may be it is the reason for it, that a particular commit has some deviations from Golang standard formatting?

**Comment by brancz** [comment]
Thanks for adapting! This lgtm now.

> PS: Travis CI will always fail if go fmt changes something relative to already commited code. I see few other pull requests failed Travis CI, may be it is the reason for it, that a particular commit has some deviations from Golang standard formatting?

Can you point me at which PRs you mean? If it's a problem then we need to fix it, but generally we want the build to fail if `go fmt` changes anything.

**Comment by opusmagnum** [comment]
I meant e.g. something like -- https://github.com/coreos/prometheus-operator/pull/950, https://travis-ci.org/coreos/prometheus-operator/jobs/335850230 but see now that the diff is obvious there (it is definitely not an invisible space) and you have already recommended how to fix it. Never mind.

Thank you for support and explanations!

**Pull request merged**
