### PR TITLE
*: Bump Prometheus to v2.4.0

### PR DESCRIPTION
**Pull request by metalmatze**
I guess we should update our Prometheus to the latest version. ☺️ 

@brancz @mxinden @squat @s-urbaniak

### CODE REVIEW

**Comment by brancz** [comment]
lgtm

**Comment by metalmatze** [comment]
I think the e2e tests are flaky...

**Comment by squat** [comment]
I’ll restart the tests

**Comment by mrueg** [comment]
Can you update to 2.4.2?

**Comment by mxinden** [comment]
> Can you update to 2.4.2?

@mrueg good point. We should do that in https://github.com/coreos/prometheus-operator/pull/1929.

**Pull request closed without merging**
