### PR TITLE
release-0.38 backport: Retain PVC metadata

### PR DESCRIPTION
**Pull request by pgier**
Backport of #3115

### CODE REVIEW

**Comment by pgier** [comment]
@paulfantom For some reason it looks like Travis is updating the vendor dir and causing this to fail.  Do you know of any recent CI changes that might cause this?

**Comment by paulfantom** [comment]
Locking jsonnet-ci image to `release-0.38` tag may fix it. I don't have other ideas :(

**Comment by pgier** [comment]
Looks like the build failures were due to a travis caching issue as @paulfantom suggested.  I deleted the cache and restarted the build and it seems ok now.

**Comment by s-urbaniak** [comment]
LGTM

**Pull request merged**
