### PR TITLE
fix node_filesystem only collect mountpoint '/' metrics

### PR DESCRIPTION
**Pull request by liuxu623**

### CODE REVIEW

**Comment by brancz** [comment]
This file is generated through jsonnet, you will also need to add that line here: 

https://github.com/coreos/prometheus-operator/blob/8254bb3aafca4df8735e8df644ef99448bb01ba3/contrib/kube-prometheus/jsonnet/kube-prometheus/node-exporter/node-exporter.libsonnet#L88

**Comment by Andor** [comment]
Let's merge it as soon as it will pass all the tests.

**Comment by brancz** [comment]
@liuxu623 I hope you don't mind, I added a commit that does some (confusing) bumps and re-generates the auto-generated parts of this repo. This should make CI pass now :slightly_smiling_face: .

**Comment by liuxu623** [comment]
@brancz Thank you very much🙂.

**Comment by metalmatze** [comment]
Awesome!

**Comment by s-urbaniak** [comment]
good catch indeed, thanks! :+1:

**Pull request merged**
