### PR TITLE
Fixing build.sh in kube-prometheus README

### PR DESCRIPTION
**Pull request by dmcnaught**
Fixing https://github.com/coreos/prometheus-operator/issues/1885

### CODE REVIEW

**Comment by brancz** [comment]
I think that’s actually correct. $1 is the first argument passed to the script and the rest means, that if it’s not specified it will default to example.jsonnet

**Comment by mxinden** [comment]
@dmcnaught for example:

```shell
➜  /tmp cat test.sh 
echo "The first argument was"
echo ${1-no argument}
➜  /tmp ./test.sh      
The first argument was
no argument
➜  /tmp ./test.sh hallo
The first argument was
hallo
➜  /tmp 
```

Not sure if this differs on Mac though.

**Comment by metalmatze** [comment]
I've tested this on my Mac and its behaviour exactly the same as documented by @mxinden.

**Comment by dmcnaught** [comment]
Ah. I forgot it could be that. I’m using zsh and it didn’t work. I can look into it more later today.

**Comment by metalmatze** [comment]
I tested that again on macOS with zsh (previously with bash).

tesh.sh:
```
#!/bin/zsh
echo "The first argument was"
echo ${1-no argument}
```

`$ zsh ./test.sh`
```
The first argument was
no argument
```

`$ zsh ./test.sh hello`
```
The first argument was
hello
```

I'd say that it works as expected on linux and macOS and with bash and zsh, thus closing.
If you happen to find that it's still an issue, please reopen.
Thanks.

**Pull request closed without merging**
