### PR TITLE
Add additional scrape configs to helm charts.

### PR DESCRIPTION
**Pull request by whypro**
It generates secret based on `additionalScrapeConfigs`yaml values.

### CODE REVIEW

**Comment by gianrubio** [comment]
ci is failing because you didn't bump the version of prometheus in kube-prometheus/requirements.yaml, please fix that.

**Comment by whypro** [comment]
Thanks. I've fixed that. @gianrubio

**Comment by gianrubio** [comment]
@whypro do you mind to rebase it again?

**Comment by whypro** [comment]
@gianrubio OK

**Comment by gianrubio** [comment]
thanks @whypro

**Pull request merged**
