### PR TITLE
thanos-s3 spec added encrypt-sse

### PR DESCRIPTION
**Pull request by astub**
updated thanos sidecar spec to be able to use server side encrypt.

Issue #1673

### CODE REVIEW

**Comment by astub** [comment]
Can I get this through. Looks like it only failed one of the build checks.

**Comment by mxinden** [comment]
@astub we are generating a whole bunch of manifests and documentation based on our source code. Could you run `make generate` in the root of the repo and commit the changes? That should fix your CI failures.

**Comment by astub** [comment]
hey im closing this pr and reopening because I don't really know how to deal with the conflict after master was updated...

**Comment by mxinden** [comment]
Hi @astub,

you would need to do the following:

Add the upstream repository as a remote:

`git remote add upstream https://github.com/osela/prometheus-operator.git`

Fetch new changes from upstream:

`git fetch upstream`

Rebase your changes on top of upstream changes:

`git rebase upstream/master`

Push the new changes to your fork:

`git push --force-with-lease`

This PR will update automatically.

Let me know if you need further advice. I am happy to help!

**Pull request closed without merging**
