### PR TITLE
Migrate to go-modules

### PR DESCRIPTION
**Pull request by kuznero**
Another version of  #2105. Ping @brancz. This version is less noisy as root module is named such that it was not necessary to change any of the imports.

### CODE REVIEW

**Comment by kuznero** [comment]
Green this time around ;)

**Comment by brancz** [comment]
Even with go-mods we would like to keep the `vendor/` directory and the related verification tooling, in order to do offline, immutable builds.

**Comment by kuznero** [comment]
@brancz I think all the necessary stuff is still in the vendor folder.

**Comment by metalmatze** [comment]
I looked into this again. Is there something blocking us from using Go modules? @brancz @squat @mxinden?
Otherwise I can continue with this, as I have a rebased branch on my machine.

**Comment by mxinden** [comment]
No reason to not use go modules from my side. :+1:

**Comment by brancz** [comment]
I've had some difficulties with Kubernetes libs and go mods. My experience has been converting from dep/glide works just fine, but starting from scratch/updating doesn't necessarily work. Can you confirm that those two also work?

**Comment by metalmatze** [comment]
Alright cool. I'll make another branch from the updated branch of this and check how an update of Kubernetes works out. If that's ok, then I will update this PR and merge Go modules. :+1:

**Comment by brancz** [comment]
My experience is ~2 months old, so may very well be fixed in newer go versions. I have no objections.

**Comment by metalmatze** [comment]
This is superseeded by https://github.com/coreos/prometheus-operator/pull/2571. Thanks for the taking the time nevertheless!

**Pull request closed without merging**
