### PR TITLE
helm/prometheus: prometheus template

### LINKED ISSUE #914: Cannot use matchExpressions syntax with Rules Selector in Prometheus Helm Chart
**What did you do?**
I deployed Prometheus using Helm.

**What did you expect to see?**
As with `serviceMonitorsSelector` I expected that the values from the Prometheus chart for `rulesSelector` can be written like this:
```
rulesSelector: {
  matchExpressions: [{key: prometheus, operator: In, values: [alertmanager, prometheus-inf]}]
}
```
This syntax only works for `serviceMonitorsSelector`.

The bug is [here](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/templates/prometheus.yaml), line 68. Comparing it to line 59, the difference is clear. 

I need to specify that matchExpressions syntax works for both. Right now I edit the Prometheus resource in Kubernetes by hand in order to achieve the same results as with `serviceMonitorSelector`. 

If you need more details, please tell me.

### PR DESCRIPTION
**Pull request by MihaiAnei**
allow Rules Selector to use other Selectors besides matchLabels

Fixes #914

### CODE REVIEW

**Comment by MihaiAnei** [comment]
Maybe I should've increased the Chart version as well?

**Comment by gianrubio** [comment]
Yes, please follow this [steps](https://github.com/coreos/prometheus-operator/tree/master/helm#how-to-contribue)

**Comment by gianrubio** [comment]
also bump kube-prometheus and it's requirements

**Comment by MihaiAnei** [comment]
I realised I forgot that after the failed travis-ci build, thanks. It should be okay now.

**Comment by gianrubio** [comment]
bumping kube-prometheus version, on green we are ready to merge!!

**Comment by gianrubio** [comment]
thanks @MihaiAnei

**Comment by andersflemmen** [comment]
Does this not break the rules.yaml template? I'm getting errors when using
```
rulesSelector:
  matchLabels:
    role: example-rules
```

**Comment by MihaiAnei** [comment]
@andersflemmen previously you could not use any other selector besides `matchLabels` with `rulesSelector`. Indeed your custom chart values need to be changed as this is a breaking change.
For example, if you need to use a `matchLabels` selector:
```
rulesSelector: {
  matchLabels: [{role: example-rules}]
}
```
or if you need a `matchExpression` (which I use most of the times):
```
rulesSelector: {
  matchExpressions: [{key: prometheus, operator: In, values: [nginx-rules, kube-etcd-rules, any-other-awesome-rules]}]
}
```

**Comment by andersflemmen** [comment]
Hmm, ok, so I have to use json inside my yaml?

**Comment by andersflemmen** [comment]
The error comes from the template file below (rules.yaml), where it seems to expect only single labels.
```
{{- if and .Values.rules.specifiedInValues .Values.rules.value }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
    {{- if .Values.rulesSelector }}
{{ toYaml .Values.rulesSelector | indent 4 }}
    {{- end }}
  name: prometheus-{{ .Release.Name }}-rules
data:
{{ toYaml .Values.rules.value | indent 2 }}
{{- end }}
```

**Comment by MihaiAnei** [comment]
@andersflemmen Indeed, you are right. I did not see that because I did not have any values in 
```
rules:
  specifiedInValues: true
  value:
```
so using (in custom values yaml)
```
rules:
  specifiedInValues: true
  value:
    groups:
    - name: prometheus.rules
      rules:
      - alert: PrometheusConfigReloadFailed
        expr: prometheus_config_last_reload_successful == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          description: Reloading Prometheus' configuration has failed for {{`{{$labels.namespace}}`}}/{{`{{$labels.pod}}`}}
```
generates
```
# Source: prometheus/templates/rules.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    chart: prometheus-0.0.24
    heritage: Tiller
    prometheus: prometheus-test
    release: prometheus-test
    matchExpressions:
    - key: prometheus
      operator: In
      values:
      - prometheus-hadm
    
  name: prometheus-prometheus-test-rules
data:
  groups:
  - name: prometheus.rules
    rules:
    - alert: PrometheusConfigReloadFailed
      annotations:
        description: Reloading Prometheus' configuration has failed for {{`{{$labels.namespace}}`}}/{{`{{$labels.pod}}`}}
      expr: prometheus_config_last_reload_successful == 0
      for: 10m
      labels:
        severity: warning
```
which, indeed, is not right. I'll think of a solution and come back with a PR.

**Pull request merged**
