### PR TITLE
kube-prometheus: Fix minor typo

### PR DESCRIPTION
**Pull request by mxinden**
@gianrubio Are there any steps for me to take to update the helm code?

Replaces https://github.com/coreos/prometheus-operator/pull/950

### CODE REVIEW

**Comment by brancz** [comment]
lgtm, I'm fine if the helm changes are a follow up

**Comment by gianrubio** [comment]
@mxinden to update the helm chart you should run this [script](https://github.com/coreos/prometheus-operator/blob/master/helm/hack/sync_kube_prometheus.py)
and [bump](https://github.com/coreos/prometheus-operator/tree/master/helm#how-to-contribue) the charts

**Comment by mxinden** [comment]
@gianrubio as this is just a typo, do you mind, if this is just automatically included in the next chart version bump?

**Comment by gianrubio** [comment]
@mxinden no worries, it'll be fixed in the next bump ;)

**Pull request merged**
