### PR TITLE
Add thanos ruler route prefix

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

Add `routePrefix` in spec

### CODE REVIEW

**Comment by simonpasquier** [comment]
Not sure why the vendor check is failing on Travis. LGTM otherwise.

**Comment by yeya24** [comment]
Yes, the CI failure is strange. I didn't change update any dependency and I cannot reproduce this problem in my local environment. Could someone help me re-trigger the Travis CI?

**Comment by brancz** [comment]
might this be a go version things?

**Comment by pgier** [comment]
@yeya24 can you rebase this?  Hopefully, the CI failure will also go away after the update.

**Comment by yeya24** [comment]
Got a flaky test here https://travis-ci.org/coreos/prometheus-operator/builds/654476206?utm_source=github_status&utm_medium=notification. Will open a PR to fix it first

**Comment by yeya24** [comment]
@pgier Hello, CI passed. Could you please take a look?

**Pull request merged**
