### PR TITLE
 RELEASE.md: Update documentation 

### PR DESCRIPTION
**Pull request by mxinden**
@metalmatze this should give a good first start. Let's improve this as you are cutting the new Prometheus Operator release.

@brancz Any major concerns?

### CODE REVIEW

**Comment by metalmatze** [comment]
Seems like a familiar process from my side. 
I will evaluate the guide and update accordingly after going with it, if something needs change.

**Comment by brancz** [comment]
What about https://github.com/coreos/prometheus-operator/blob/master/RELEASE.md ?

**Comment by metalmatze** [comment]
Oh. Maybe we can merge some of the commands and little details that @mxinden now has already written with the RELEASE.md that's already there?

**Comment by mxinden** [comment]
Haha, @brancz completely forgot about that.

https://github.com/coreos/prometheus-operator/blob/master/RELEASE.md needs some updates though. I will follow up with that.

**Comment by mxinden** [comment]
Would you mind taking another look @brancz @metalmatze?

**Comment by brancz** [comment]
Awesome! lgtm :+1:

**Comment by metalmatze** [comment]
Thanks for these improvements. If I encounter anything missing, I'll create a follow up PR.

**Pull request merged**
