### PR TITLE
Add link to PersistentVolumeClaim reference

### PR DESCRIPTION
**Pull request by aknuds1**
In the API docs, link to the PersistentVolumeClaim reference.

### CODE REVIEW

**Comment by brancz** [comment]
Those links are actually auto generated through the `cmd/apidocgen` tool. Could you just add the link [here](https://github.com/coreos/prometheus-operator/blob/master/cmd/apidocgen/main.go#L38-L45) and run `make generate` to verify it works? That would be of huge help! :slightly_smiling_face:

**Comment by aknuds1** [comment]
@brancz Done. I also modified the Makefile to use `embedmd` and `apidocgen` from `$GOPATH/bin/` in case the user doesn't have `$GOPATH/bin` in $PATH or they have other versions in there.

**Comment by brancz** [comment]
@coreosbot test this please

**Comment by brancz** [comment]
lgtm thanks a lot @aknuds1 !

**Comment by aknuds1** [comment]
Thanks @brancz!

**Pull request merged**
