### PR TITLE
Remove creationTimestamp from manifests

### PR DESCRIPTION
**Pull request by emmanuelCarre**
Hi,

Thank you for this great tool.

`creationTimestamp` is field fill by server side. Force value to null will trigger an resource update whereas nothing change on next apply; it is break idempotency. 

Regards,

### CODE REVIEW

**Comment by emmanuelCarre** [comment]
Hum... strange. Tests are failed since I rebase. I didn't think it is link to my change. There is a way to re-run CI test step?

**Comment by emmanuelCarre** [comment]
There is similar issue on master: https://travis-ci.org/coreos/prometheus-operator/jobs/646753326?utm_medium=notification&utm_source=github_status

**Comment by emmanuelCarre** [comment]
Yes I did it. There is no change:
```bash
$ git status
On branch fix-creationTimestamp-null
Your branch is up to date with 'origin/fix-creationTimestamp-null'.

nothing to commit, working tree clean
$ make generate-in-docker            
docker run --rm -u="1000:1000" -v "/home/ecarre/.cache/go-build:/.cache/go-build" -v "/home/ecarre/projects/github.com/coreos/prometheus-operator:/go/src/github.com/coreos/prometheus-operator:Z" -w "/go/src/github.com/coreos/prometheus-operator" -e GO111MODULE=on -e USER=deadbeef quay.io/coreos/po-tooling make  --always-make generate
/go/bin/controller-gen object:headerFile=./.header \
	paths=./pkg/apis/monitoring/v1
/go/bin/controller-gen "crd:preserveUnknownFields=false" paths=./pkg/apis/monitoring/v1 output:crd:dir=./example/prometheus-operator-crd
cat ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml | \
sed s/plural\:\ prometheus/plural\:\ prometheuses/ | \
sed s/prometheus.monitoring.coreos.com/prometheuses.monitoring.coreos.com/ \
> ./example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
rm ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml
sed -i "/\ \ creationTimestamp\:\ null/d" example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
/go/bin/controller-gen "crd:preserveUnknownFields=false" paths=./pkg/apis/monitoring/v1 output:crd:dir=./example/prometheus-operator-crd
cat ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml | \
sed s/plural\:\ prometheus/plural\:\ prometheuses/ | \
sed s/prometheus.monitoring.coreos.com/prometheuses.monitoring.coreos.com/ \
> ./example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
rm ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml
sed -i "/\ \ creationTimestamp\:\ null/d" example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
/go/bin/controller-gen "crd:preserveUnknownFields=false" paths=./pkg/apis/monitoring/v1 output:crd:dir=./example/prometheus-operator-crd
cat ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml | \
sed s/plural\:\ prometheus/plural\:\ prometheuses/ | \
sed s/prometheus.monitoring.coreos.com/prometheuses.monitoring.coreos.com/ \
> ./example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
rm ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml
sed -i "/\ \ creationTimestamp\:\ null/d" example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
/go/bin/controller-gen "crd:preserveUnknownFields=false" paths=./pkg/apis/monitoring/v1 output:crd:dir=./example/prometheus-operator-crd
cat ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml | \
sed s/plural\:\ prometheus/plural\:\ prometheuses/ | \
sed s/prometheus.monitoring.coreos.com/prometheuses.monitoring.coreos.com/ \
> ./example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
rm ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml
sed -i "/\ \ creationTimestamp\:\ null/d" example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
/go/bin/controller-gen "crd:preserveUnknownFields=false" paths=./pkg/apis/monitoring/v1 output:crd:dir=./example/prometheus-operator-crd
cat ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml | \
sed s/plural\:\ prometheus/plural\:\ prometheuses/ | \
sed s/prometheus.monitoring.coreos.com/prometheuses.monitoring.coreos.com/ \
> ./example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
rm ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml
sed -i "/\ \ creationTimestamp\:\ null/d" example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
/go/bin/controller-gen "crd:preserveUnknownFields=false" paths=./pkg/apis/monitoring/v1 output:crd:dir=./example/prometheus-operator-crd
cat ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml | \
sed s/plural\:\ prometheus/plural\:\ prometheuses/ | \
sed s/prometheus.monitoring.coreos.com/prometheuses.monitoring.coreos.com/ \
> ./example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
rm ./example/prometheus-operator-crd/monitoring.coreos.com_prometheus.yaml
sed -i "/\ \ creationTimestamp\:\ null/d" example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
/go/bin/go-bindata \
-mode 420 -modtime 1 \
-o  pkg/apis/monitoring/v1/bindata.go \
-pkg v1 \
example/prometheus-operator-crd
cat example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml   | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/alertmanager-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheus-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/servicemonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml     | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/podmonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheusrule-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/thanosruler-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml   | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/alertmanager-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheus-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/servicemonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml     | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/podmonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheusrule-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/thanosruler-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml   | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/alertmanager-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheus-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/servicemonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml     | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/podmonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheusrule-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/thanosruler-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml   | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/alertmanager-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheus-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/servicemonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml     | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/podmonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheusrule-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/thanosruler-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml   | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/alertmanager-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheus-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/servicemonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml     | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/podmonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheusrule-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/thanosruler-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml   | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/alertmanager-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheus-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/servicemonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml     | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/podmonitor-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/prometheusrule-crd.libsonnet
cat example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml    | gojsontoyaml -yamltojson > jsonnet/prometheus-operator/thanosruler-crd.libsonnet
sed -i                                                            \
	"s/prometheusOperator: 'v.*',/prometheusOperator: 'v0.35.0',/" \
	jsonnet/prometheus-operator/prometheus-operator.libsonnet;
cd scripts/generate; /go/bin/jb install;
Cloning into 'vendor/.tmp/jsonnetpkg-prometheus-operator-e36b013401ce2211f26820d89734220164609b86599578733'...
done.
Note: checking out 'e36b013401ce2211f26820d89734220164609b86'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at e36b0134 Merge pull request #3000 from yeya24/ruler-add-label
>>> Installed prometheus-operator version e36b013401ce2211f26820d89734220164609b86
Cloning into 'vendor/.tmp/jsonnetpkg-ksonnet-0d2f82676817bbf9e4acf6495b2090205f323b9f678314728'...
Note: checking out '0d2f82676817bbf9e4acf6495b2090205f323b9f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 0d2f826 Generate ksonnet.beta.4 based on Kubernetes 1.14
>>> Installed ksonnet version 0d2f82676817bbf9e4acf6495b2090205f323b9f
scripts/generate/build-rbac-prometheus-operator.sh
scripts/generate/build-rbac-prometheus-operator.sh
scripts/generate/build-rbac-prometheus-operator.sh
scripts/generate/build-rbac-prometheus-operator.sh
scripts/generate-bundle.sh
scripts/generate/build-non-rbac-prometheus-operator.sh
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/po-docgen api pkg/apis/monitoring/v1/types.go pkg/apis/monitoring/v1/thanos_types.go > Documentation/api.md
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/po-docgen compatibility > Documentation/compatibility.md
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
$ git status
On branch fix-creationTimestamp-null
Your branch is up to date with 'origin/fix-creationTimestamp-null'.

nothing to commit, working tree clean
```

**Comment by pgier** [comment]
This looks like the same test failure we were seeing in #3007 when trying to upgrade the default Prometheus version, although I'm not sure why it would show up in this PR since I don't see any changes that would affect it.  I restarted the failing job, just to check if this was a flake.

**Comment by emmanuelCarre** [comment]
Wonderful! It works :)
Thank you @pgier

**Comment by pgier** [comment]
If possible, I'd prefer that our CRD generation tool does right thing initially instead of modifying the CRD yaml files in the Makefile.  I created an issue in the controller-tools (https://github.com/kubernetes-sigs/controller-tools/issues/402) to see if this can be fixed there first, or if there is some reason why they include the `creationTimestamp` field.

**Comment by emmanuelCarre** [comment]
Thank you @pgier. I will follow the issue on controller-tools and take a look if I have time/knowledge to contribute. 

I work around this issue with jsonnet function  `std.prune` onto imported libsonnet file.

**Pull request closed without merging**
