### PR TITLE
Upgrade jsonnet bundler

### PR DESCRIPTION
**Pull request by pgier**
Not sure if we want to start upgrading projects yet to jb v0.2.0, but I thought I would create this PR while I was thinking about it after some testing.

### CODE REVIEW

**Comment by pgier** [comment]
@metalmatze says we should start using jsonnet-bundler v0.2.0, so I think this should be ok to merge on green

**Comment by brancz** [comment]
lgtm on green. There is even a newer version coming soon that will feature canonical import paths, but one after another :)

**Comment by elisiano** [comment]
somewhat related to this, can a `--version` flag be added to `jb`? right now it's confusing for end users to know what they installed.

**Comment by pgier** [comment]
@elisiano There is now a `--version` flag in v0.2.0, just not in v0.1.0.

**Pull request merged**
