### PR TITLE
contrib/kube-prometheus: Remove compatibility node exporter recording rules

### PR DESCRIPTION
**Pull request by metalmatze**
With https://github.com/coreos/prometheus-operator/pull/2096 merged the node exporter queries have been updated and we should be able to remove the compatibility recording rules, as they now use the node_exporter:v0.16 metrics directly.

/cc @brancz @squat

### CODE REVIEW

**Comment by squat** [comment]
dang needs a rebase, otherwise looks great!

**Comment by metalmatze** [comment]
Yep. It's the 5th conflict today where I need to resolve the revision in `jsonnetfile.lock.json` :man_shrugging: 
Maybe I should take the time to fix jb there :sweat_smile:

**Comment by mxinden** [comment]
@metalmatze would you mind rebasing once more. Let me know if I can be of any help.

**Comment by metalmatze** [comment]
Rebased and conflict in `jsonnetfile.lock.json` resolved.

**Comment by mxinden** [comment]
Thanks @metalmatze!

**Pull request merged**
