### PR TITLE
Strict Namespace Selection Parameter

### PR DESCRIPTION
**Pull request by midnightconman**
Refer to the following PR for more information: https://github.com/coreos/prometheus-operator/pull/813

### CODE REVIEW

**Comment by midnightconman** [comment]
@fabxc @ant31 @brancz, can you guys comment on this PR? I would like to keep the conversation going.

**Comment by brancz** [comment]
We are actively thinking of designs of how we could make this work, unfortunately it's not as easy as this PR. Once we have more concrete ideas we will share them with everyone.

**Comment by midnightconman** [comment]
Great News! Thank you Brancz, is there any way / place we can check on progress around this?

**Comment by mxinden** [comment]
@midnightconman This PR is related: https://github.com/coreos/prometheus-operator/pull/1227

**Pull request closed without merging**
