### PR TITLE
Added Helm RBAC instructions to README

### LINKED ISSUE #260: helm install opsgoodness/prometheus-operator causes rbac error on k8s 1.5.5
**What did you do?**
```bash
helm repo add opsgoodness http://charts.opsgoodness.com
helm install opsgoodness/prometheus-operator
```
**What did you expect to see?**
adding prometheus operator

**What did you see instead? Under which circumstances?**
>>>
--- github/coreos » helm install opsgoodness/prometheus-operator
Error: release plinking-numbat failed: clusterroles.rbac.authorization.k8s.io "plinking-numbat-prometheus-operator" is forbidden: attempt to grant extra privileges: [{[*] <nil> [] [configmaps] [] []} {[*] <nil> [] [secrets] [] []} {[delete] <nil> [] [pods] [] []} {[list] <nil> [] [pods] [] []} {[create] <nil> [] [services] [] []} {[get] <nil> [] [services] [] []} {[update] <nil> [] [services] [] []} {[create] <nil> [] [endpoints] [] []} {[get] <nil> [] [endpoints] [] []} {[update] <nil> [] [endpoints] [] []} {[list] <nil> [] [nodes] [] []} {[watch] <nil> [] [nodes] [] []} {[*] <nil> [apps] [statefulsets] [] []} {[create] <nil> [extensions] [thirdpartyresources] [] []} {[get] <nil> [extensions] [thirdpartyresources] [] []} {[*] <nil> [monitoring.coreos.com] [alertmanagers] [] []} {[*] <nil> [monitoring.coreos.com] [prometheuses] [] []} {[*] <nil> [monitoring.coreos.com] [servicemonitors] [] []}] user=&{system:serviceaccount:kube-system:default 62998b8b-1407-11e7-9890-0659fdf912f6 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[{[create] <nil> [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] <nil> [] [] [] [/version /api /api/* /apis /apis/*]}] ruleResolutionErrors=[]

**Environment**
Created on AWS with kops 1.5.3, k8s 1.5.5
* Kubernetes version information:
```bash
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:23:49Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.5", GitCommit:"894ff23729bbc0055907dd3a496afb725396adda", GitTreeState:"clean", BuildDate:"2017-03-22T00:17:51Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

kops 1.5.3

* Manifests:

* Prometheus Operator Logs:

### PR DESCRIPTION
**Pull request by mgoodness**
Resolves #260

### CODE REVIEW

**Comment by dmcnaught** [comment]
@mgoodness 
On my k8s 1.5.5 cluster, following the 1.5.x instructions gives me this error:
```bash
--- contrib/kube-prometheus » kubectl -n kube-system create sa tiller
Error from server (AlreadyExists): serviceaccounts "tiller" already exists
--- contrib/kube-prometheus » cat <<EOF | kubectl create -f -
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
EOF
Error from server (Forbidden): error when creating "STDIN": clusterrolebindings.rbac.authorization.k8s.io "tiller" is forbidden: attempt to grant extra privileges: [{[*] <nil> [*] [*] [] []} {[*] <nil> [] [] [] [*]}] user=&{admin admin [system:authenticated] map[]} ownerrules=[{[create] <nil> [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] <nil> [] [] [] [/version /api /api/* /apis /apis/*]}] ruleResolutionErrors=[]
```

**Comment by mgoodness** [comment]
@dmcnaught OK, I see what the problem is. According to https://github.com/coreos/prometheus-operator/issues/275#issuecomment-292628382, you don't have RBAC enabled in your cluster. The new section of the README states that these steps are only required if RBAC _is_ enabled.

However, the chart installs the prometheus-operator with RBAC support by default. I failed to document in the README how to disable that. Let me address that.

**Comment by dmcnaught** [comment]
Great - that works. Thanks @mgoodness 
```bash
--- contrib/kube-prometheus » helm install --name my-release opsgoodness/prometheus-operator --set rbacEnable=false
NAME:   my-release
LAST DEPLOYED: Fri Apr  7 14:26:57 2017
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> extensions/v1beta1/Deployment
NAME                            DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
my-release-prometheus-operator  1        1        1           1          32s


NOTES:
The Prometheus Operator has been installed. Check its status by running:
  kubectl --namespace default get pods \
    -l "app=prometheus-operator,release=my-release"

Visit https://github.com/coreos/prometheus-operator for instructions on how
to create & configure Alertmanager and Prometheus instances using the Operator.
```

**Comment by mgoodness** [comment]
Excellent - thank you for the feedback!

**Comment by dmcnaught** [comment]
My pleasure. Is there an easy route to deploy kube-prometheus from here, or is that WIP.
I opened another ticket against the /hack/cluster-monitoring/deploy that used to deploy on k8s 1.5.
Seems like things a are little up in the air at the moment, maybe I should wait a little while. 😄 
I'm happy to test WIP against my config.

**Comment by mgoodness** [comment]
I intend to spend quite a bit of time this weekend at least getting charts added that will instantiate Prometheus & Alertmanager instances. A full kube-prometheus chart will take more work. Definitely the goal, though!

**Comment by brancz** [comment]
thanks @mgoodness lgtm! and thanks @dmcnaught for testing!

**Pull request merged**
