### PR TITLE
Fix examples

### PR DESCRIPTION
**Pull request by maxlim0**
- fix ServiceAccount name according to bundle.yaml

### CODE REVIEW

**Comment by brancz** [comment]
Can you explain these changes? The Prometheus instances are intended to have their own service account.

**Comment by maxlim0** [comment]
The bundle.yaml created ServiceAccont: prometheus-operator
In examples we using SA = prometheus, in this case, I can't use examples to correct provision pods.

**Comment by brancz** [comment]
A separate ServiceAccount needs to be provisioned for the Prometheus instances.

**Comment by maxlim0** [comment]
Should bundle.yaml be compatible with the examples?

**Comment by brancz** [comment]
Yes, but they are distinct responsibilities so we'll never have prometheus and prometheus operator use the same serviceaccount.

**Pull request closed without merging**
