### PR TITLE
Support for storage.tsdb.retention.size for prometheus 2.7+

### PR DESCRIPTION
**Pull request by Dymanik**
Since Prometheus 2.7 supports the storage.tsdb.retention.size flag to limit the storage usage.
Added support  for it in "PrometheusSpec" as "RetentionSize". 
fixes: #2563

### CODE REVIEW

**Comment by brancz** [comment]
This needs a `make clean generate-in-docker` from the root of the repo.

**Comment by Dymanik** [comment]
It needed a ```make format```. The latest build failed on a test that succeeded before, can we rerun the build?

**Comment by brancz** [comment]
Looks like that was a flake, I restarted the build.

**Comment by brancz** [comment]
Thanks! lgtm :+1:

**Pull request merged**
