### PR TITLE
Increase memory limits to avoid OOMKilled

### PR DESCRIPTION
**Pull request by gianrubio**
Related to https://github.com/kubernetes/kube-state-metrics/issues/112#issuecomment-292965833

### CODE REVIEW

**Comment by fabxc** [comment]
If we get OOM killed at 50 the requested memory should probably be adjusted already to 100Mi and the limit to 200Mi.

**Comment by gianrubio** [comment]
Should I do in this PR now?

**Comment by fabxc** [comment]
Yea, that would be best.

**Comment by gianrubio** [comment]
Done!

**Comment by brancz** [comment]
Awesome thanks! We should definitely benchmark kube-state-metrics so we can do some vertical autoscaling as its memory consumption grows linearly with the cluster size.

**Comment by brancz** [comment]
Just for the record, do you have an estimate count of objects you have in your Kubernetes cluster @gianrubio ?

**Comment by gianrubio** [comment]
@brancz I'm not sure if this it you mean

``` 
# etcdctl ls --recursive /registry|wc -l
1060 
```

## v0.3.0
screen shot 2017-04-10 at 17 03 30

## v0.4.1 (looks lighter)

screen shot 2017-04-10 at 17 22 48

**Pull request merged**
