### PR TITLE
subpath creation while mounting prometheus data volume

### PR DESCRIPTION
**Pull request by Rastusik**
This resolves https://github.com/coreos/prometheus-operator/issues/29

### CODE REVIEW

**Comment by brancz** [comment]
I don't have a cluster with a GlusterFS provisioner at hand. If you could compile and try it out on your cluster and confirm that it fixes #29 that would be great. In general I don't see a problem with this. Maybe a tiny nitpick, I think I would prefer to call the subpath `db` or `prometheus-db`, but feel free to ignore.

**Comment by Rastusik** [comment]
I have already compiled and tested the change yesterday and it worked perfectly :) ... regarding the folder name, I can change that if you want me to, no problem, just say the word

**Comment by brancz** [comment]
Thank you very much! Could you just change it to `prometheus-db` and run `gofmt` then I'll merge, build and push the new image 👍 .

**Comment by Rastusik** [comment]
done

**Comment by brancz** [comment]
Perfect! Thank you very much! LGTM 👍

**Pull request merged**
