### PR TITLE
Preserve pod metadata in custom resources

### LINKED ISSUE #3041: podMetadata feature no longer functional
**What happened?**

All edits to the `podMetadata` field of a Prometheus object are discarded by kube-apiserver.

**Did you expect to see something different?**

Data should be stored by kube-apiserver.

**How to reproduce it (as minimally and precisely as possible)**:

Try to set a label or annotation using podMetadata.

**Environment**

* Prometheus Operator version: 0.36.0

* Kubernetes version information: 1.17.2

* Kubernetes cluster kind: kops

* Manifests:

```
podMetadata:
  labels:
    foo: bar
```

* Prometheus Operator Logs: N/A (data never makes it that far.

**Anything else we need to know?**:

This was caused by a mix of #2855 where controller-tools didn't recurse into the ObjectMeta struct so it was changed in the generated CRD to be just a plain `type: object` with no fields. And then #2903 which disabled saving unknown fields so any data set on `podMetadata` will be discarded by apiserver since it has no declared fields. The same issue might be affecting other fields, I didn't do a check of the full diff from #2855.

Getting controller-tools to recurse outside of the current package is an old bug, we've run into it on our operators a few times, but hopefully an upgrade there would fix it? If not, I'm sure Solly could assist.

### PR DESCRIPTION
**Pull request by pgier**
This applies a patch (https://github.com/kubernetes-sigs/controller-tools/pull/395) the controller-gen binary to generate validation for PodMetadata and fix #3041.  Since this is not merged yet into upstream controller-tools, I'm not sure if we want to merge it here.  So for now this PR is just for testing.

### CODE REVIEW

**Comment by coderanger** [comment]
Built and deployed, and it seems happy now :) Thanks! If you don't want to go with a pre-release patch to c-t, another option would be to just make our own struct there instead of directly using ObjectMeta. Which might help anyway since only a few fields from ObjectMeta really make sense there?

**Comment by pgier** [comment]
> another option would be to just make our own struct there instead of directly using ObjectMeta.

@coderanger That sounds like it could work, and it's similar to some of the comments in controller-tools about how they are planning to handle ObjectMeta, so hopefully somewhat in-line with their future changes.

**Comment by pgier** [comment]
@coderanger It seems we are only using the Labels and Annotations from the ObjectMeta type.  The rest is just ignored anyway.  So I changed the type of PodMetadata to a new custom type PodMeta which includes only Labels and Annotations.  WDYT?

**Comment by coderanger** [comment]
@pgier Heh, was just finishing up a patch to do the same to try and save you the trouble, but 👍 from me. I don't think any other fields make sense to be use controlled. In some galaxy brain mode technically you could allow for non-controller owner refs but I think the use case there is too wonky.

**Pull request merged**
