### PR TITLE
Adding label selector for AlertManager objects discovery filtering

### PR DESCRIPTION
**Pull request by neoludo**
Recently a parameter has been added to filter by label selectors prometheus objects.
I did the same for alertmanagers

### CODE REVIEW

**Comment by brancz** [comment]
Looks like this needs a `make vendor`.

**Comment by neoludo** [comment]
> make vendor
I've done it just right now : "vendor is up to date"

**Comment by brancz** [comment]
Are you using the same version of go as CI is?

> go version go1.12.6 linux/amd64

**Comment by brancz** [comment]
(you also may need to do `make --always-make vendor`)

**Comment by neoludo** [comment]
It was just a sorting issue in vendor/module.txt

**Comment by neoludo** [comment]
Hi Frederic,

Have you planned a release soon ?

Thanks for your answer
Ludo

**Comment by brancz** [comment]
Thanks! Lgtm :+1:

**Comment by brancz** [comment]
We’ve recently done a release, I think it’ll be a couple of weeks until we do another minor release.

**Comment by neoludo** [comment]
Thanks Frederic...
I'll keep my own tag in my private repository for now and stay in touch to switch on released version as soon as it's available. No urgence.

**Pull request merged**
