### PR TITLE
Update Thanos vendoring to include config reloader fixes

### PR DESCRIPTION
**Pull request by juliusv**
See https://github.com/coreos/prometheus-operator/issues/2501

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
@metalmatze I guess the new Docker image and associated version changes will need to be done by you CoreOS people?

**Comment by metalmatze** [comment]
Yes, exactly. We need to do a release and Travis will do/push the rest. :relaxed:

**Comment by juliusv** [comment]
Cool!

**Comment by juliusv** [comment]
@metalmatze An unrelated mesh test flaked out in one of the CI builds, can you trigger a re-run?

**Comment by s-urbaniak** [comment]
restarted the build, let's see how this goes :crossed_fingers:

**Comment by brancz** [comment]
lgtm :+1: thanks @juliusv!

**Pull request merged**
