### PR TITLE
Added grafana and grafana watcher resources to templates

### PR DESCRIPTION
**Pull request by stijndehaes**
This pull request removes the hardcoded resources from the grafana helm chart and makes them configurable.

### CODE REVIEW

**Comment by stijndehaes** [comment]
Same test as on master fails: TestPrometheusOnlyUpdatedOnRelevantChanges

**Comment by gianrubio** [comment]
@mxinden any idea why CI is failing?

**Comment by gianrubio** [comment]
@stijndehaes can you rebase from master ?

**Comment by stijndehaes** [comment]
@gianrubio has been rebased

**Comment by gianrubio** [comment]
thanks @stijndehaes

**Pull request merged**
