### PR TITLE
Set SecurityContext on Prometheus StatefulSet

### LINKED ISSUE #541: Permission denied using volumeClaimTemplate w/ automatically provisioned storage
**What did you do?**

I ran the latest versions of the Prometheus Operator (v0.11.0 and v0.11.1) configured to use the new Prometheus v2.0.0-beta.0 version with persistent storage on the Prometheus pods using the following storage config:
```
...
  storage:
    volumeClaimTemplate:
      metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: ssd
      spec:
        resources:
          requests:
            storage: 10Gi
...
```

Note: `ssd` is a `StorageClass` for AWS EBS gp2 volumes.

**What did you expect to see?**

Pods on the Prometheus StatefulSet launching correctly.

**What did you see instead? Under which circumstances?**

The `prometheus-k8s-0` pod fails to start due to a permissions issue on the persistent volume and ends up in a `CrashLoopBackOff` state. Inspection on the node reveals the mount point of the persistent volume created by the Prometheus Operator is owned by `root`, which is not the case for mount points of persistent volumes on a regular StatefulSet using the same `StorageClass`.

The pods launch correctly when the `volumeClaimTemplate` configuration is omitted.

This issue seems similar to #518, although in this case storage is being provisioned automatically.

**Environment**

* Kubernetes version information:

Tested on both 1.6.2 and 1.6.4.
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0", GitCommit:"8996efde382d88f0baef1f015ae801488fcad8c4", GitTreeState:"clean", BuildDate:"2017-05-19T21:11:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Custom terraform deploy on AWS using CoreOS 1409.7.0

* Manifests:

```
see contrib/kube-prometheus/manifests
```

* Prometheus Operator Logs:

```
time="2017-08-04T16:56:37Z" level=info msg="Starting prometheus (version=2.0.0-beta.0, branch=master, revision=2b5d9159537cbd123219296121e05244e26c0940)" source="main.go:202" 
time="2017-08-04T16:56:37Z" level=info msg="Build context (go=go1.8.3, user=root@fc24486243df, date=20170712-12:21:13)" source="main.go:203" 
time="2017-08-04T16:56:37Z" level=info msg="Host details (Linux 4.11.11-coreos #1 SMP Tue Jul 18 23:06:59 UTC 2017 x86_64 prometheus-k8s-0 (none))" source="main.go:204" 
time="2017-08-04T16:56:37Z" level=info msg="Starting tsdb" source="main.go:216" 
time="2017-08-04T16:56:37Z" level=error msg="Opening storage failed: open DB in /var/prometheus/data: open /var/prometheus/data/969552713: permission denied" source="main.go:219" 
```

### PR DESCRIPTION
**Pull request by Capitrium**
Currently, when the Prometheus Operator is configured to use persistent storage on a cluster configured to use [dynamic volume provisioning](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#dynamic), pods on the Prometheus StatefulSet fail to launch due to a permissions error when accessing the storage mount point.

```
time="2017-08-04T16:56:37Z" level=info msg="Starting prometheus (version=2.0.0-beta.0, branch=master, revision=2b5d9159537cbd123219296121e05244e26c0940)" source="main.go:202" 
time="2017-08-04T16:56:37Z" level=info msg="Build context (go=go1.8.3, user=root@fc24486243df, date=20170712-12:21:13)" source="main.go:203" 
time="2017-08-04T16:56:37Z" level=info msg="Host details (Linux 4.11.11-coreos #1 SMP Tue Jul 18 23:06:59 UTC 2017 x86_64 prometheus-k8s-0 (none))" source="main.go:204" 
time="2017-08-04T16:56:37Z" level=info msg="Starting tsdb" source="main.go:216" 
time="2017-08-04T16:56:37Z" level=error msg="Opening storage failed: open DB in /var/prometheus/data: open /var/prometheus/data/969552713: permission denied" source="main.go:219"
```

Setting the following SecurityContext on the Prometheus StatefulSet allow the pods to access the storage mount point when using dynamically provisioned volumes:
```yaml
securityContext:
  fsGroup: 2000
  runAsUser: 1000
  runAsNonRoot: true
```

```
time="2017-08-07T19:49:45Z" level=info msg="Starting prometheus (version=2.0.0-beta.0, branch=master, revision=2b5d9159537cbd123219296121e05244e26c0940)" source="main.go:202" 
time="2017-08-07T19:49:45Z" level=info msg="Build context (go=go1.8.3, user=root@fc24486243df, date=20170712-12:21:13)" source="main.go:203" 
time="2017-08-07T19:49:45Z" level=info msg="Host details (Linux 4.11.11-coreos #1 SMP Tue Jul 18 23:06:59 UTC 2017 x86_64 prometheus-k8s-0 (none))" source="main.go:204" 
time="2017-08-07T19:49:45Z" level=info msg="Starting tsdb" source="main.go:216" 
time="2017-08-07T19:49:50Z" level=info msg="tsdb started" source="main.go:222
...
```

Fixes #541

### CODE REVIEW

**Comment by brancz** [comment]
This looks great! Thanks for your effort! Our CI infra for this project is currently having some difficulties, I'll get right to this PR once we've fixed the problem.

**Comment by brancz** [comment]
@coreosbot test this please.

**Comment by brancz** [comment]
Unfortunately due to some changes in the build infra we had to do some changes and this PR therefore needs a rebase. Sorry about that!

**Comment by Capitrium** [comment]
No worries! Should be all set now.

**Comment by brancz** [comment]
I think something went wrong while rebasing, the commits from master should not end up being shown in this PR.

**Pull request closed without merging**
