### PR TITLE
Helm Grafana - Add extraVars

### PR DESCRIPTION
**Pull request by sebglon**
#929

### CODE REVIEW

**Comment by sebglon** [comment]
@gianrubio Yes sorry, made.

**Comment by sebglon** [comment]
@gianrubio could you merge it?

**Comment by lfaoro** [comment]
hello everyone! This pull request is exactly what we need! +1

Once you merge it into master will you also make available a helm Chart release that I could use with helm upgrade?

**Comment by sebglon** [comment]
yes it's that

**Pull request merged**
