### PR TITLE
Clarify targetPort in endpoint

### PR DESCRIPTION
**Pull request by vincent-pli**
Fix issue: #3354

### CODE REVIEW

**Comment by brancz** [comment]
API docs are generated, you need to also change this here https://github.com/coreos/prometheus-operator/blob/c9758cf8de3ef21973c03e98d8e4c01a2d4bf0a9/pkg/apis/monitoring/v1/types.go#L697

**Comment by brancz** [comment]
I recommend to just run

```bash
make --always-make format generate
```

this will format and re-generate everything correctly, then CI should pass

**Comment by vincent-pli** [comment]
@brancz 
Thanks for helping 😄

**Comment by brancz** [comment]
Thanks for bearing with us! :) 

lgtm :tada:

**Pull request merged**
