### PR TITLE
Update comment link for API convention for spec and status

### PR DESCRIPTION
**Pull request by DhritiShikhar**
The old link `https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#spec-and-status` is not available anymore.

### CODE REVIEW

**Comment by DhritiShikhar** [comment]
@LiliC can you review this PR?

**Comment by LiliC** [comment]
@DhritiShikhar Can you run `make generate-in-docker ` and it should regenerate the files for you correctly. Maybe commit the generated files separately afterward. Thanks!

**Comment by DhritiShikhar** [comment]
@LiliC Done here a5a274b

**Comment by DhritiShikhar** [comment]
@LiliC Can we merge this PR?

**Pull request merged**
