### PR TITLE
Remove dependency on replace directive

### PR DESCRIPTION
**Pull request by jpreese**
Simplifies the `go.mod` file and removes the need for the `replace` directive

### CODE REVIEW

**Comment by jpreese** [comment]
I may need some insight on the `go mod vendor` and `git diff` step of the CI pipeline. My guess would be that it's for other modules that depend on us, to ensure compile time compatibility, but it seems really aggressive in its approach (just checking a diff).

Changes that would not impact compilation at all, e.g. comments, would fail this step. Am I misunderstanding its intent?

**Comment by paulfantom** [comment]
`go mod vendor` ensures that all dependencies needed to build an operator are present in `vendor` directory. This, in turn, ensures a fully reproducible build without needing to access external sources and having a `git diff` check in CI is a small price to pay for such feature.

**Comment by jpreese** [comment]
Thanks for the response @paulfantom. I understand the reasoning behind `vendor`, I'm a little unclear about the `git diff` check. With how it's currently implemented, I'm not sure how you would, for example, _update_ a current dependency, because the diffs wouldn't match. 

Am I misunderstanding what that step in the CI is actually doing?

**Comment by paulfantom** [comment]
> I'm not sure how you would, for example, update a current dependency, because the diffs wouldn't match.

Run `go mod vendor` locally and add `vendor/` directory in a commit. If `go.mod` didn't change during development, then `vendor/` also won't differ and check will be green.

**Comment by paulfantom** [comment]
Also if you want to pin dependency to some version, you would use `replace` directive in `go.mod`, run `go mod vendor` and commit both things into repository.

**Comment by paulfantom** [comment]
> Which is why I was failing to understand how we update our dependencies if we can never change vendor

There is nothing preventing you from re-vendoring and thus changing content of `vendor/` directory. We are doing it constantly, for example last time it was done in https://github.com/coreos/prometheus-operator/pull/2820 (which also made this PR incompatible). However we don't patch things in `vendor/` directory, if there is an issue, we try to fix it at the source.

The majority of this PR was done in #2820 and `replace` directives need to be here as they provide us a locking mechanism for necessary dependencies. I am closing this, but if you think this is still beneficial, please rebase and reopen PR.

**Pull request closed without merging**
