### PR TITLE
Update Kubernetes client libraries to 1.14.0 release

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
I have also added pruning to Gopkg.toml. I can remove that if you prefer so.

```
[prune]
  go-tests = true
  unused-packages = true
```

**Comment by tamalsaha** [comment]
I tried to run tests locally against minikube. The failed test on Travis worked but some other test is failing.

```
$ make test-e2e REPO=appscode/prometheus-operator
go test -timeout 55m -v ./test/e2e/  --kubeconfig=/home/tamal/.kube/config --operator-image=appscode/prometheus-operator:40265873 -count=1
=== RUN   TestAllNS
=== RUN   TestAllNS/x
=== RUN   TestAllNS/x/AMClusterGossipSilences
=== RUN   TestAllNS/x/PromVersionMigration
=== PAUSE TestAllNS/x/PromVersionMigration
=== RUN   TestAllNS/x/AMMeshAfterRollingUpdate
=== RUN   TestAllNS/x/PromResourceUpdate
=== PAUSE TestAllNS/x/PromResourceUpdate
=== RUN   TestAllNS/x/PromAdditionalScrapeConfig
=== PAUSE TestAllNS/x/PromAdditionalScrapeConfig
=== RUN   TestAllNS/x/PromDiscovery
=== PAUSE TestAllNS/x/PromDiscovery
=== RUN   TestAllNS/x/PromAlertmanagerDiscovery
=== PAUSE TestAllNS/x/PromAlertmanagerDiscovery
=== RUN   TestAllNS/x/PromGetBasicAuthSecret
=== PAUSE TestAllNS/x/PromGetBasicAuthSecret
=== RUN   TestAllNS/x/AMMeshInitialization
=== RUN   TestAllNS/x/AMMeshInitialization/amVersionv0-14-0
=== RUN   TestAllNS/x/AMMeshInitialization/amVersionv0-16-2
=== RUN   TestAllNS/x/AMReloadConfig
=== RUN   TestAllNS/x/PromCreateDeleteCluster
=== PAUSE TestAllNS/x/PromCreateDeleteCluster
=== RUN   TestAllNS/x/PromScaleUpDownCluster
=== PAUSE TestAllNS/x/PromScaleUpDownCluster
=== RUN   TestAllNS/x/PromStorageUpdate
=== PAUSE TestAllNS/x/PromStorageUpdate
=== RUN   TestAllNS/x/Thanos
=== PAUSE TestAllNS/x/Thanos
=== RUN   TestAllNS/x/AMScaling
=== RUN   TestAllNS/x/PromNoServiceMonitorSelector
=== PAUSE TestAllNS/x/PromNoServiceMonitorSelector
=== RUN   TestAllNS/x/PromMultiplePrometheusRulesSameNS
=== PAUSE TestAllNS/x/PromMultiplePrometheusRulesSameNS
=== RUN   TestAllNS/x/PromMultiplePrometheusRulesDifferentNS
=== PAUSE TestAllNS/x/PromMultiplePrometheusRulesDifferentNS
=== RUN   TestAllNS/x/PromWhenDeleteCRDCleanUpViaOwnerRef
=== PAUSE TestAllNS/x/PromWhenDeleteCRDCleanUpViaOwnerRef
=== RUN   TestAllNS/x/AMExposingWithKubernetesAPI
=== RUN   TestAllNS/x/PromRulesExceedingConfigMapLimit
=== PAUSE TestAllNS/x/PromRulesExceedingConfigMapLimit
=== RUN   TestAllNS/x/PromOnlyUpdatedOnRelevantChanges
=== PAUSE TestAllNS/x/PromOnlyUpdatedOnRelevantChanges
=== RUN   TestAllNS/x/AMZeroDowntimeRollingDeployment
=== RUN   TestAllNS/x/PromReloadConfig
=== PAUSE TestAllNS/x/PromReloadConfig
=== RUN   TestAllNS/x/PromAdditionalAlertManagerConfig
=== PAUSE TestAllNS/x/PromAdditionalAlertManagerConfig
=== RUN   TestAllNS/x/PromReloadRules
=== PAUSE TestAllNS/x/PromReloadRules
=== RUN   TestAllNS/x/PromDiscoverTargetPort
=== PAUSE TestAllNS/x/PromDiscoverTargetPort
=== RUN   TestAllNS/x/AMCreateDeleteCluster
=== RUN   TestAllNS/x/AMVersionMigration
=== RUN   TestAllNS/x/AMStorageUpdate
=== RUN   TestAllNS/x/PromExposingWithKubernetesAPI
=== PAUSE TestAllNS/x/PromExposingWithKubernetesAPI
=== RUN   TestAllNS/x/PromOpMatchPromAndServMonInDiffNSs
=== PAUSE TestAllNS/x/PromOpMatchPromAndServMonInDiffNSs
=== CONT  TestAllNS/x/PromVersionMigration
=== CONT  TestAllNS/x/PromMultiplePrometheusRulesSameNS
=== CONT  TestAllNS/x/PromCreateDeleteCluster
=== CONT  TestAllNS/x/PromNoServiceMonitorSelector
=== CONT  TestAllNS/x/Thanos
=== CONT  TestAllNS/x/PromStorageUpdate
=== CONT  TestAllNS/x/PromScaleUpDownCluster
=== CONT  TestAllNS/x/PromRulesExceedingConfigMapLimit
2019/04/23 13:03:20 setting up querier with args:  [query --log.level=debug --query.replica-label=prometheus_replica --cluster.peers=thanos-peers.allns-x-thanos-pqfjpi-0.svc:10900]
2019/04/23 13:03:55 Unexpected number of results from query. Got 0, expected 4. retrying...
2019/04/23 13:04:00 Unexpected number of results from query. Got 0, expected 4. retrying...
2019/04/23 13:04:05 Unexpected number of results from query. Got 0, expected 4. retrying...
```

**Comment by metalmatze** [comment]
The test on Travis is a flake. I've restarted those.

**Comment by tamalsaha** [comment]
Thanks @metalmatze ! Tests are passing now. :tada:

**Comment by brancz** [comment]
Lgtm thanks a lot for doing this! :)

**Pull request merged**
