### PR TITLE
pkg/prometheus/promcfg.go: Only append relabelings if EnforcedNamespaceLabel value is set

### PR DESCRIPTION
**Pull request by LiliC**
Only append relabelings if EnforcedNamespaceLabel value is set.

cc @s-urbaniak @brancz

### CODE REVIEW

**Comment by brancz** [comment]
lgtm on green

**Comment by LiliC** [comment]
Not sure what we could add to our e2e tests to improve them? As our openshift e2e tests caught this. I added a unit test that failed before this change.

**Comment by brancz** [comment]
We could run promtool checks against all generated configs?

**Comment by LiliC** [comment]
Not sure our e2e tests cover this case, because the pods would not be up and running as prometheus would reject the invalid configuration.

**Comment by brancz** [comment]
Oops I understand now. https://github.com/coreos/prometheus-operator/blob/be1c7825adbfe0cd6e3bf94dec77060be968f752/pkg/prometheus/promcfg.go#L557

This line needs to be outside of the if statement. We need to enforce no matter if there are relabeling rules defined or not by the user.

**Comment by LiliC** [comment]
@brancz good catch! PTAL, thanks!

**Comment by brancz** [comment]
lgtm on greene

**Comment by s-urbaniak** [comment]
lgtm :+1:

**Pull request merged**
