### PR TITLE
prometheus: Add ability to whitelist Kubernetes labels

### LINKED ISSUE #695: Propagate service monitored label
**What did you do?**
my service have labels pfid.
My servicemonitor use label pfid on selector
But those label is not propagate on prometheus metrics

**What did you expect to see?**
i want to have access on all or select of labels available on service to prometheus metrics

### PR DESCRIPTION
**Pull request by brancz**
Closes #695

RE: #1129

@ant31 @fabxc @mxinden 

/cc @olvesh

### CODE REVIEW

**Comment by opusmagnum** [comment]
I have tested this new Service-label-to-metric-label feature on a build from the master-branch, it works as expected. Thanks to @brancz and @ant31 for a very useful addition!

**Comment by SivaKrishna05** [comment]
i want to scrape the deployment meta labels i am unable to seeing in the each scrape @brancz how to scrape deployment lables

**Comment by brancz** [comment]
@SivaKrishna05 deployment labels are unknown to the Prometheus service discovery, your only chance is to use metrics from kube-state-metrics to join and correlate this data.

**Comment by SivaKrishna05** [comment]
metadata:
  labels:
    gitBranch: {{ .Values.gitBranch | quote }}
    gitOrgId: {{ .Values.gitOrgId | quote }}
    gitOrgName: {{ .Values.gitOrgName | quote }}
    gitRepoId: {{ .Values.gitRepoId | quote }}
    gitRepoName: {{ .Values.gitRepoName | quote }}
i have labels like this on each deployment to get to know which pod is related to which repo like that  in your context there is no way of getting this labels in my each datapoint.

**Comment by brancz** [comment]
You can put these labels on your service and then whitelist them in the servicemonitor, then you will get them as labels on the metrics.

**Pull request merged**
