### PR TITLE
kube-prometheus/manifests: Upgrade api resource versions from apps/v1beta2 to apps/v1

### PR DESCRIPTION
**Pull request by Aracki**
Upgraded old deprecated Deployment/DaemonSet API resource versions.

### CODE REVIEW

**Comment by brancz** [comment]
All of these are generated, and I'm afraid the library we use for generation still uses the old APIs. We will need to talk to the maintainers to get that updated.

**Comment by Aracki** [comment]
It's hard for new contributors who have never used jsonnet/ksonnet to follow [contrib/kube-prometheus/contribution guidline](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#contributing). I'm not sure it it's because of an old APIs, but I am always getting errors for `make generate-in-docker`.

**Comment by Aracki** [comment]
With `make clean generate-in-docker` or `make generate-in-docker` the tail I am getting:

```
HEAD is now at fa521f4e0... Merge pull request #10392 from mitake/cn-gateway
rm -rf manifests
./build.sh
+ set -o pipefail
+ rm -rf manifests
+ mkdir manifests
+ jsonnet -J vendor -m manifests example.jsonnet
+ xargs '-I{}' sh -c 'cat {} | gojsontoyaml > {}.yaml; rm -f {}' -- '{}'
make[1]: Leaving directory '/go/src/github.com/coreos/prometheus-operator/contrib/kube-prometheus'
hack/generate/build-non-rbac-prometheus-operator.sh
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
go install github.com/coreos/prometheus-operator/cmd/po-docgen
go: disabling cache (/.cache/go-build) due to initialization failure: mkdir /.cache: permission denied
/go/bin/po-docgen api pkg/apis/monitoring/v1/types.go > Documentation/api.md
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
```

When I do it with `sudo` I am getting:

```
HEAD is now at fa521f4e0... Merge pull request #10392 from mitake/cn-gateway
rm -rf manifests
./build.sh
+ set -o pipefail
+ rm -rf manifests
+ mkdir manifests
+ jsonnet -J vendor -m manifests example.jsonnet
+ xargs '-I{}' sh -c 'cat {} | gojsontoyaml > {}.yaml; rm -f {}' -- '{}'
make[1]: Leaving directory '/go/src/github.com/coreos/prometheus-operator/contrib/kube-prometheus'
hack/generate/build-non-rbac-prometheus-operator.sh
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
go install github.com/coreos/prometheus-operator/cmd/po-docgen
/go/bin/po-docgen api pkg/apis/monitoring/v1/types.go > Documentation/api.md
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/po-docgen compatibility > Documentation/compatibility.md
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
/go/bin/embedmd -w `find Documentation -name "*.md" | grep -v vendor`
```

Nothing gets generated. When I do these commands inside `/contrib/kube-prometheus` I am getting: `make: Nothing to be done for 'generate'`.

I need to go through generete-in-docker script and jsonnet documentation (which I don't find very friendly) to understand better what are the steps how you are building manifests in this repository. 😕

**Comment by brancz** [comment]
Do the changes you did get reverted by running those commands? That's what should be happening. Updating these version is a larger task, as the jsonnet library we use first has to be updated.

**Comment by Aracki** [comment]
No. Nothing gets reverted. I think I should close the PR. 

Maybe I will do some contribution after I have some basic understanding of jsonnet.

**Comment by mgoodness** [comment]
> We will need to talk to the maintainers to get that updated.

I've also been wondering how to tackle this. With ksonnet being retired (or at least handed off), any thoughts about how the project should proceed?

**Comment by brancz** [comment]
the ksonnet library is generated from openapi, so it shouldn't be a big deal at all to update this

**Comment by metalmatze** [comment]
kube-prometheus just moved to https://github.com/coreos/kube-prometheus. 
See [contrib/kube-prometheus/README.md](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/README.md) for details.

Thank you for your contribution and sorry for the inconvenience!

**Pull request closed without merging**
