### PR TITLE
Add support for custom Thanos sidecar resources

### PR DESCRIPTION
**Pull request by bosgood**
This PR corresponds to the issue https://github.com/coreos/prometheus-operator/issues/1745.

### CODE REVIEW

**Comment by brancz** [comment]
lgtm :+1: thanks a lot for taking care of this!

**Comment by bosgood** [comment]
Thanks @brancz! I didn't see any formal release process detailed in the README, do you have any info on when this might be available in a tagged release?

**Comment by brancz** [comment]
You're in luck, we've just started the process :slightly_smiling_face: https://github.com/coreos/prometheus-operator/pull/1751

**Comment by bosgood** [comment]
Fantastic, thanks for maintaining this project so actively.

**Pull request merged**
