### PR TITLE
Helm pathPrefix config fix

### PR DESCRIPTION
**Pull request by kovszilard**
Fixes https://github.com/coreos/prometheus-operator/issues/1596

### CODE REVIEW

**Comment by eonicle** [comment]
When will it be merged? It would be great not to silence constantly firing alert.

**Comment by kovszilard** [comment]
@brancz, @gianrubio I opened this PR a long time ago and version numbers were out of date so I fixed it and rebased on top of the current master. Can you please review it?

**Comment by brancz** [comment]
Sorry for the inconvenience, but the prometheus-operator and kube-prometheus helm charts are currently being migrated to the upstream stable helm charts. Because of this we are currently not accepting any pull requests. We apologize for the inconvenience, but this is necessary for the migration to actually happen. We announced this here: https://github.com/coreos/prometheus-operator/tree/master/helm#warning

You can view the progress and help [here](https://github.com/coreos/prometheus-operator/issues/592) and [here](https://github.com/helm/charts/pull/6765).

Thank you for your understanding! :slightly_smiling_face:

**Comment by metalmatze** [comment]
The Helm chart has moved to https://github.com/helm/charts/tree/master/stable/prometheus-operator please open a PR there.
Thank you for your contribution!

**Pull request closed without merging**
